import { RouteObject } from "react-router";

import AuthGuard from "@/middleware/AuthGuard";
import { DynamicLayout } from "../layouts/DynamicLayout";
import DynamicRedirect from "./DynamicRedirect";
import { lazyPageRoute } from "./routeHelpers";

const dashboardRoutes: RouteObject[] = [
  lazyPageRoute("home", () => import("@/app/pages/dashboards/home")),
  lazyPageRoute("insurer-management/insurer", () => import("@/app/pages/dashboards/insurerManagement/insurer"), "insurer"),
  lazyPageRoute("insurer-management/add-insurer", () => import("@/app/pages/dashboards/insurerManagement/insurer/AddInsurerForm"), "insurer"),
  lazyPageRoute("insurer-management/add-contact-person", () => import("@/app/pages/dashboards/insurerManagement/contactPerson/form"), "insurer"),
  lazyPageRoute("insurer-management/add-contact-person/:id", () => import("@/app/pages/dashboards/insurerManagement/contactPerson/form"), "insurer"),
  lazyPageRoute("insurer-management/view-insurer/:id", () => import("@/app/pages/dashboards/insurerManagement/insurer/AddInsurerForm"), "insurer"),
  lazyPageRoute("insurer-management/ic-onboarding-check-list", () => import("@/app/pages/dashboards/insurerManagement/IcCheckList"), "insurer"),
  lazyPageRoute("insurer-management/office", () => import("@/app/pages/dashboards/insurerManagement/offices"), "insurer"),
  lazyPageRoute("insurer-management/add-office", () => import("@/app/pages/dashboards/insurerManagement/offices/add-office/form"), "insurer"),
  lazyPageRoute("insurer-management/view-office/:id", () => import("@/app/pages/dashboards/insurerManagement/offices/add-office/form"), "insurer"),
  lazyPageRoute("insurer-management/contact-person", () => import("@/app/pages/dashboards/insurerManagement/contactPerson"), "insurer"),
  lazyPageRoute("insurer-management/brand-history", () => import("@/app/pages/dashboards/insurerManagement/brandHistory"), "insurer"),
  lazyPageRoute("insurer-management/merger", () => import("@/app/pages/dashboards/insurerManagement/merger"), "insurer"),
  lazyPageRoute("insurer-management/office-hierarchy", () => import("@/app/pages/dashboards/insurerManagement/InsurerOfficeHierarchy/index"), "insurer"),
  lazyPageRoute("tpa-management/branches", () => import("@/app/pages/AdminDepartment/tpabranches/index"), "tpa"),
  lazyPageRoute("tpa-management/tpa", () => import("@/app/pages/AdminDepartment/tpa/form"), "tpa"),
  lazyPageRoute("tpa-management/add-tpa", () => import("@/app/pages/AdminDepartment/tpa/form"), "tpa"),
  lazyPageRoute("tpa-management/add-branch", () => import("@/app/pages/AdminDepartment/tpabranches/form"), "tpa"),
  lazyPageRoute("tpa-management/escalation-matrix", () => import("@/app/pages/AdminDepartment/escalation-matrix/HREscalationMatrix"), "tpa"),
  lazyPageRoute("tpa-management/view-branch/:id", () => import("@/app/pages/AdminDepartment/tpabranches/form"), "tpa"),
  lazyPageRoute("mbm-management/dashboard", () => import("@/app/pages/dashboards/mbmmanagement/dashboard/index"), "master-product"),
  lazyPageRoute("mbm-management/dashboard/:id", () => import("@/app/pages/dashboards/mbmmanagement/dashboard/detail"), "master-product"),
  lazyPageRoute("master-management/master-product", () => import("@/app/pages/dashboards/mbmmanagement/master-product"), "master-product"),
  lazyPageRoute("master-management/master-product/:id", () => import("@/app/pages/dashboards/mbmmanagement/master-product/detail"), "master-product"),
  lazyPageRoute("mbm-management/policy-benefit", () => import("@/app/pages/dashboards/mbmmanagement/maker-checker"), "master-product"),
  lazyPageRoute("mbm-management/policy-benefit/:id", () => import("@/app/pages/dashboards/mbmmanagement/maker-checker/detail"), "master-product"),
  lazyPageRoute("inward-management/inward", () => import("@/app/pages/dashboards/enrollmentsystem/PolicyDetails/index"), "enrollment"),
  lazyPageRoute("inward-management/psu-inward", () => import("@/app/pages/dashboards/enrollmentsystem/PolicyDetails/psuinward/index"), "enrollment"),
  lazyPageRoute("user-management/users", () => import("@/app/pages/dashboards/usermanagement/Users/index"), "enrollment"),
  lazyPageRoute("enrolment-system/assignment-management", () => import("@/app/pages/dashboards/enrollmentsystem/assignment-management/index"), "enrollment"),
  lazyPageRoute("master-management/corporate-group", () => import("@/app/pages/dashboards/enrollmentsystem/corporateGroup/index"), "enrollment"),
  lazyPageRoute("master-management/corporate", () => import("@/app/pages/dashboards/enrollmentsystem/corporate/index."), "enrollment"),
  lazyPageRoute("master-management/add-corporate", () => import("@/app/pages/dashboards/enrollmentsystem/corporate/FormIndex"), "enrollment"),
  lazyPageRoute("master-management/view-corporate/:id", () => import("@/app/pages/dashboards/enrollmentsystem/corporate/FormIndex"), "enrollment"),
  lazyPageRoute("master-management/add-corporate-group", () => import("@/app/pages/dashboards/enrollmentsystem/corporateGroup/FormIndex"), "enrollment"),
  lazyPageRoute("master-management/view-corporate-group/:id", () => import("@/app/pages/dashboards/enrollmentsystem/corporateGroup/FormIndex"), "enrollment"),
  lazyPageRoute("master-management/view-corporate/:id", () => import("@/app/pages/dashboards/enrollmentsystem/corporateGroup/form"), "enrollment"),
  lazyPageRoute("master-management/broker", () => import("@/app/pages/dashboards/enrollmentsystem/broker/index"), "enrollment"),
  lazyPageRoute("master-management/add-broker", () => import("@/app/pages/dashboards/enrollmentsystem/broker/FormIndex"), "enrollment"),
  lazyPageRoute("master-management/view-broker/:id", () => import("@/app/pages/dashboards/enrollmentsystem/broker/FormIndex"), "enrollment"),
  lazyPageRoute("inward-management/view-inward-document/:id", () => import("@/app/pages/dashboards/enrollmentsystem/PolicyDetails/InwardView"), "enrollment"),
  lazyPageRoute("enrolment-system/policy-mapping", () => import("@/app/pages/dashboards/enrollmentsystem/dashboard/policy-mapping/index"), "provider"),
  lazyPageRoute("enrolment-system/dashboard", () => import("@/app/pages/dashboards/enrollmentsystem/dashboard/index"), "enrollment"),
  lazyPageRoute("enrolment-system/admin-dashboard", () => import("@/app/pages/dashboards/enrollmentsystem/dashboard/components/admindashboard/index"), "enrollment"),
  lazyPageRoute("enrolment-system/policy-search", () => import("@/app/pages/dashboards/enrollmentsystem/policy-search/index"), "enrollment"),
  lazyPageRoute("enrolment-system/e-card-configuration", () => import("@/app/pages/dashboards/enrollmentsystem/dashboard/ecard/index"), "enrollment"),
  lazyPageRoute("enrolment-system/e-cards", () => import("@/app/pages/dashboards/enrollmentsystem/dashboard/ecard/listing/index"), "enrollment"),
  lazyPageRoute("enrolment-system/corporate-enrolment", () => import("@/app/pages/dashboards/enrollmentsystem/dashboard/corporate/CorporateInward"), "enrollment"),
  lazyPageRoute("enrolment-system/member-data", () => import("@/app/pages/dashboards/enrollmentsystem/dashboard/corporate/MemberData"), "enrollment"),
  lazyPageRoute("enrolment-system/member-data/exception-details", () => import("@/app/pages/dashboards/enrollmentsystem/dashboard/corporate/ExceptionDetails"), "enrollment"),
  lazyPageRoute("enrolment-system/endorsement-member-data", () => import("@/app/pages/dashboards/enrollmentsystem/dashboard/corporate/EndorsementMember"), "enrollment"),
  lazyPageRoute("enrolment-system/corporate-enrolment/:id", () => import("@/app/pages/dashboards/enrollmentsystem/dashboard/components/CorporateEnrollmentLayout"), "enrollment"),
  lazyPageRoute("enrolment-system/retail-inward", () => import("@/app/pages/dashboards/enrollmentsystem/dashboard/retail/RetailInward"), "enrollment"),
  lazyPageRoute("master-management/agent", () => import("@/app/pages/dashboards/enrollmentsystem/agent/index"), "enrollment"),
  lazyPageRoute("master-management/add-agent", () => import("@/app/pages/dashboards/enrollmentsystem/agent/FormIndex"), "enrollment"),
  lazyPageRoute("master-management/view-agent/:id", () => import("@/app/pages/dashboards/enrollmentsystem/agent/FormIndex"), "enrollment"),
  lazyPageRoute("provider-masters/dashboard/inward/:inwardNo", () => import("@/app/pages/dashboards/providerManagernt/provider-master/excluded-provider/inward/index"), "provider"),
  lazyPageRoute("provider-masters/dashboard", () => import("@/app/pages/dashboards/providerManagernt/dashboard/index"), "provider"),
  lazyPageRoute("provider-masters/empanel", () => import("@/app/pages/dashboards/providerManagernt/hospitalEmpanelment/landing/index"), "provider"),
  lazyPageRoute("provider-masters/create", () => import("@/app/pages/dashboards/providerManagernt/hospitalEmpanelment/registrationForm/index"), "provider"),
  lazyPageRoute("provider-masters/providers/:id/agreement/new-agreement", () => import("@/app/pages/dashboards/providerManagernt/provider-master/provider/detail/index"), "provider"),
  lazyPageRoute("provider-masters/providers/:id/agreement/:agreementId/edit", () => import("@/app/pages/dashboards/providerManagernt/provider-master/provider/detail/index"), "provider"),
  lazyPageRoute("provider-masters/providers/:id/agreement/:agreementId/view", () => import("@/app/pages/dashboards/providerManagernt/provider-master/provider/detail/index"), "provider"),
  lazyPageRoute("provider-masters/providers/:id/soc/:socId/edit", () => import("@/app/pages/dashboards/providerManagernt/provider-master/provider/detail/index"), "provider"),
  lazyPageRoute("provider-masters/providers/:id/soc/:socId/view", () => import("@/app/pages/dashboards/providerManagernt/provider-master/provider/detail/index"), "provider"),
  lazyPageRoute("provider-masters/providers/:id/discount/:discountId/edit", () => import("@/app/pages/dashboards/providerManagernt/provider-master/provider/detail/index"), "provider"),
  lazyPageRoute("provider-masters/providers/:id/discount/:discountId/view", () => import("@/app/pages/dashboards/providerManagernt/provider-master/provider/detail/index"), "provider"),
  lazyPageRoute("provider-masters/providers/:id/provider-mapped-with-ic-and-corporate/provider-mapped-with-ic/new-ic-mapping", () => import("@/app/pages/dashboards/providerManagernt/provider-master/provider/detail/index"), "provider"),
  lazyPageRoute("provider-masters/providers/:id/provider-mapped-with-ic-and-corporate/provider-mapped-with-ic/add-restriction", () => import("@/app/pages/dashboards/providerManagernt/provider-master/provider/detail/index"), "provider"),
  lazyPageRoute("provider-masters/providers/new", () => import("@/app/pages/dashboards/providerManagernt/provider-master/provider/add/index"), "provider"),
  lazyPageRoute("provider-masters/providers/:id/owner/new", () => import("@/app/pages/dashboards/providerManagernt/provider-master/provider/detail/index"), "provider"),
  lazyPageRoute("provider-masters/providers/:id/owner/:ownerId/edit", () => import("@/app/pages/dashboards/providerManagernt/provider-master/provider/detail/index"), "provider"),
  lazyPageRoute("provider-masters/providers/:id/network-mapping/insurer/:mappingId/view", () => import("@/app/pages/dashboards/providerManagernt/provider-master/provider/detail/index"), "provider"),
  lazyPageRoute("provider-masters/providers/:id/network-mapping/insurer/:mappingId/edit", () => import("@/app/pages/dashboards/providerManagernt/provider-master/provider/detail/index"), "provider"),
  lazyPageRoute("provider-masters/providers/:id/network-mapping/corporate/:mappingId/view", () => import("@/app/pages/dashboards/providerManagernt/provider-master/provider/detail/index"), "provider"),
  lazyPageRoute("provider-masters/providers/:id/network-mapping/corporate/:mappingId/edit", () => import("@/app/pages/dashboards/providerManagernt/provider-master/provider/detail/index"), "provider"),
  lazyPageRoute("provider-masters/providers/:id/provider-restriction/insurer/:restrictionId/view", () => import("@/app/pages/dashboards/providerManagernt/provider-master/provider/detail/index"), "provider"),
  lazyPageRoute("provider-masters/providers/:id/provider-restriction/insurer/:restrictionId/edit", () => import("@/app/pages/dashboards/providerManagernt/provider-master/provider/detail/index"), "provider"),
  lazyPageRoute("provider-masters/providers/:id/provider-restriction/corporate/:restrictionId/view", () => import("@/app/pages/dashboards/providerManagernt/provider-master/provider/detail/index"), "provider"),
  lazyPageRoute("provider-masters/providers/:id/provider-restriction/corporate/:restrictionId/edit", () => import("@/app/pages/dashboards/providerManagernt/provider-master/provider/detail/index"), "provider"),
  lazyPageRoute("provider-masters/providers/:id/provider-restriction/insurer/:entityId/add", () => import("@/app/pages/dashboards/providerManagernt/provider-master/provider/detail/index"), "provider"),
  lazyPageRoute("provider-masters/providers/:id/provider-restriction/corporate/:entityId/add", () => import("@/app/pages/dashboards/providerManagernt/provider-master/provider/detail/index"), "provider"),
  lazyPageRoute("provider-masters/providers/:id/provider-restriction/insurer/:entityId", () => import("@/app/pages/dashboards/providerManagernt/provider-master/provider/detail/index"), "provider"),
  lazyPageRoute("provider-masters/providers/:id/provider-restriction/corporate/:entityId", () => import("@/app/pages/dashboards/providerManagernt/provider-master/provider/detail/index"), "provider"),
  lazyPageRoute("provider-masters/providers/:id/network-mapping/insurer", () => import("@/app/pages/dashboards/providerManagernt/provider-master/provider/detail/index"), "provider"),
  lazyPageRoute("provider-masters/providers/:id/network-mapping/corporate", () => import("@/app/pages/dashboards/providerManagernt/provider-master/provider/detail/index"), "provider"),
  lazyPageRoute("provider-masters/providers/:id/:tabSlug", () => import("@/app/pages/dashboards/providerManagernt/provider-master/provider/detail/index"), "provider"),
  lazyPageRoute("provider-masters/providers/:id", () => import("@/app/pages/dashboards/providerManagernt/provider-master/provider/detail/ProviderHospitalDetailRedirect"), "provider"),
  lazyPageRoute("provider-masters/providers", () => import("@/app/pages/dashboards/providerManagernt/provider-master/provider/list/index"), "provider"),
  lazyPageRoute("provider-masters/excluded-hospitals/bulk-exclude/inward/:inwardNo", () => import("@/app/pages/dashboards/providerManagernt/provider-master/excluded-provider/index"), "provider"),
  lazyPageRoute("provider-masters/excluded-hospitals/bulk-exclude", () => import("@/app/pages/dashboards/providerManagernt/provider-master/excluded-provider/index"), "provider"),
  lazyPageRoute("provider-masters/excluded-hospitals", () => import("@/app/pages/dashboards/providerManagernt/provider-master/excluded-provider/index"), "provider"),
  lazyPageRoute("provider-masters/rohini-master", () => import("@/app/pages/dashboards/providerManagernt/provider-master/rohini-master/index"), "provider"),
  lazyPageRoute("provider-masters/ic-provider-code-master", () => import("@/app/pages/dashboards/providerManagernt/provider-master/ic-provider-code-master/index"), "provider"),
  lazyPageRoute("provider-masters/ic-provisioning/add", () => import("@/app/pages/dashboards/providerManagernt/provider-master/ic-provisioning/FormIndex"), "provider"),
  lazyPageRoute("provider-masters/ic-provisioning/:id/edit", () => import("@/app/pages/dashboards/providerManagernt/provider-master/ic-provisioning/FormIndex"), "provider"),
  lazyPageRoute("provider-masters/ic-provisioning", () => import("@/app/pages/dashboards/providerManagernt/provider-master/ic-provisioning/index"), "provider"),
  lazyPageRoute("provider-masters/bank-verification/inward/:inwardNo", () => import("@/app/pages/dashboards/providerManagernt/provider-master/bank-verification/index"), "provider"),
  lazyPageRoute("provider-masters/bank-verification/upload", () => import("@/app/pages/dashboards/providerManagernt/provider-master/bank-verification/index"), "provider"),
  lazyPageRoute("provider-masters/bank-verification", () => import("@/app/pages/dashboards/providerManagernt/provider-master/bank-verification/index"), "provider"),
  lazyPageRoute("provider-masters/excludetableview", () => import("@/app/pages/dashboards/providerManagernt/excludetableview/index"), "provider"),
  lazyPageRoute("provider-masters/masters", () => import("@/app/pages/dashboards/providerManagernt/masters/ProviderMastersPage"), "provider"),
  lazyPageRoute("provider-masters/masters/add", () => import("@/app/pages/dashboards/providerManagernt/masters/AddProviderMasterPage"), "provider"),
  lazyPageRoute("provider-masters/masters/:masterKey/create", () => import("@/app/pages/dashboards/providerManagernt/masters/AddProviderMasterPage"), "provider"),
  lazyPageRoute("provider-masters/masters/:masterKey/edit", () => import("@/app/pages/dashboards/providerManagernt/masters/AddProviderMasterPage"), "provider"),
  lazyPageRoute("provider-masters/masters/:masterKey/:recordId/edit", () => import("@/app/pages/dashboards/providerManagernt/masters/AddProviderMasterPage"), "provider"),
  lazyPageRoute("provider-masters/ic-corporate-mapping/add-new-network/inward/:inwardNo/process", () => import("@/app/pages/dashboards/providerManagernt/provider-master/ic-corporate-mapping/index"), "provider"),
  lazyPageRoute("provider-masters/ic-corporate-mapping/add-new-network/inward/:inwardNo", () => import("@/app/pages/dashboards/providerManagernt/provider-master/ic-corporate-mapping/index"), "provider"),
  lazyPageRoute("provider-masters/ic-corporate-mapping/add-new-network", () => import("@/app/pages/dashboards/providerManagernt/provider-master/ic-corporate-mapping/index"), "provider"),
  lazyPageRoute("provider-masters/ic-corporate-mapping", () => import("@/app/pages/dashboards/providerManagernt/provider-master/ic-corporate-mapping/index"), "provider"),
  lazyPageRoute("provider-masters/soc-management", () => import("@/app/pages/dashboards/providerManagernt/soc-management/index"), "provider"),
  //Ram
  lazyPageRoute("benefits-configuration/benefits-master", () => import("@/app/pages/BenefitsConfiguration/Masters/index"), ""),
  lazyPageRoute("benefits-configuration/benefits-master/add-tnc-form/:id", () => import("@/app/pages/BenefitsConfiguration/Masters/Forms/AddTnCForm"), ""),
  lazyPageRoute("benefits-configuration/benefits-master/ailment-procedure/:id", () => import("@/app/pages/BenefitsConfiguration/Masters/Forms/AddAilmentProcedure"), ""),
  lazyPageRoute("benefits-configuration/benefits-master/edit-disease/:id", () => import("@/app/pages/BenefitsConfiguration/Masters/Forms/AddDisease"), ""),
  lazyPageRoute("benefits-configuration/benefits-master/edit-procedure/:id", () => import("@/app/pages/BenefitsConfiguration/Masters/Forms/AddProcedure"), ""),
  lazyPageRoute("benefits-configuration/benefits-master/ailment-procedure", () => import("@/app/pages/BenefitsConfiguration/Masters/Forms/AddAilmentProcedure"), ""),
  lazyPageRoute("benefits-configuration/benefits-master/add-disease", () => import("@/app/pages/BenefitsConfiguration/Masters/Forms/AddDisease"), ""),
  lazyPageRoute("benefits-configuration/benefits-master/add-procedure", () => import("@/app/pages/BenefitsConfiguration/Masters/Forms/AddProcedure"), ""),
  lazyPageRoute("benefits-configuration/benefits-master/benefit-limit", () => import("@/app/pages/BenefitsConfiguration/Masters/Forms/AddBenifitLimitForm"), ""),
  lazyPageRoute("benefits-configuration/benefits-master/benefit-limit/:id", () => import("@/app/pages/BenefitsConfiguration/Masters/Forms/AddBenifitLimitForm"), ""),
];

/**
 * Protected routes configuration
 * These routes require authentication to access
 * Uses AuthGuard middleware to verify user authentication
 */
const protectedRoutes: RouteObject = {
  id: "protected",
  Component: AuthGuard,
  children: [
    {
      Component: DynamicLayout,
      children: [
        {
          index: true,
          element: <DynamicRedirect />,
        },
        {
          path: "",
          children: [
            {
              index: true,
              element: <DynamicRedirect />,
            },
            ...dashboardRoutes,
          ],
        },
      ],
    },
  ],
};

export { protectedRoutes };
