/** Field keys for `GET /v1/provider-job/status?inwardNo=`. */
export const PROVIDER_JOB_STATUS_API_KEYS = {
  success: "success",
  status: "status",
  message: "message",
  data: "data",
  inwardNo: "inwardNo",
  jobStatus: "jobStatus",
  startTime: "startTime",
  endTime: "endTime",
  progress: "progress",
  stagingStep: "stagingStep",
  mappingStep: "mappingStep",
  stepStatus: "status",
  rowsRead: "rowsRead",
  rowsWritten: "rowsWritten",
  created: "created",
  alreadyMapped: "alreadyMapped",
  mapped: "mapped",
  failed: "failed",
  totalRows: "totalRows",
  error: "error",
  userMessage: "userMessage",
  errorCode: "errorCode",
  failedStep: "failedStep",
  technicalDetail: "technicalDetail",
  validationErrors: "validationErrors",
  sheet: "sheet",
  rowType: "rowType",
  missingColumns: "missingColumns",
} as const;
