import { useState } from 'react';
import { Link, useLocation } from 'react-router';
import { ArrowRight, ArrowUpRight, Plus, Download, Files, Clock3, ShieldCheck, CircleCheck, CalendarDays, Hospital, Users, Activity, ChevronRight } from 'lucide-react';
import { BarChart, Bar, XAxis, CartesianGrid, ResponsiveContainer, Tooltip } from 'recharts';
import { Action, Badge, PageHeading, SectionLink } from './components';
import { exportCsv } from './exportCsv';
import { useRecords } from './useRecords';

const weekly = [{ name: 'Mon', completed: 42, pending: 12 }, { name: 'Tue', completed: 58, pending: 18 }, { name: 'Wed', completed: 48, pending: 14 }, { name: 'Thu', completed: 72, pending: 20 }, { name: 'Fri', completed: 64, pending: 12 }, { name: 'Sat', completed: 86, pending: 18 }, { name: 'Sun', completed: 76, pending: 12 }];
const monthly = [{ name: 'Week 1', completed: 204, pending: 62 }, { name: 'Week 2', completed: 278, pending: 54 }, { name: 'Week 3', completed: 312, pending: 78 }, { name: 'Week 4', completed: 356, pending: 46 }];

export default function DashboardPage() {
  const { pathname } = useLocation();
  const provider = pathname.includes('provider-masters');
  const admin = pathname.includes('admin-dashboard') || pathname === '/home';
  const { records } = useRecords(provider ? 'providers' : 'enrolments');
  const { records: users } = useRecords('users');
  const [period, setPeriod] = useState('Last 7 days');
  const chart = period === 'Last 7 days' ? weekly : monthly;
  const base = provider ? '/provider-masters/providers' : '/enrolment-system/corporate-enrolment';
  const pending = records.filter(r => /processing|pending|renewal/i.test(r.status)).length;
  const review = records.filter(r => /review/i.test(r.status)).length;
  const complete = records.filter(r => /^(Active|Completed|Approved)$/.test(r.status)).length;
  const title = provider ? 'Provider overview' : admin ? 'Operations overview' : 'Enrolment overview';
  const metrics = [
    { title: provider ? 'Network providers' : 'Total enrolments', value: records.length, note: provider ? 'Across your healthcare network' : 'Corporate policy batches', icon: provider ? Hospital : Files, tone: 'teal', path: base },
    { title: provider ? 'Renewals due' : 'In processing', value: pending, note: provider ? 'Agreements awaiting renewal' : 'Ready for your next action', icon: Clock3, tone: 'amber', path: `${base}?status=${provider ? 'Renewal due' : 'Processing'}` },
    { title: provider ? 'Under review' : 'Quality review', value: review, note: 'Awaiting verification', icon: ShieldCheck, tone: 'blue', path: `${base}?status=${provider ? 'In review' : 'QC review'}` },
    { title: provider ? 'Active providers' : 'Completed', value: complete, note: provider ? 'Available in your network' : 'Successfully enrolled', icon: CircleCheck, tone: 'green', path: `${base}?status=${provider ? 'Active' : 'Completed'}` },
  ];
  const distribution = [{ label: provider ? 'Active' : 'Completed', value: complete, color: '#168b7f' }, { label: provider ? 'Renewal due' : 'Processing / pending', value: pending, color: '#edb455' }, { label: 'Quality review', value: review, color: '#7195bd' }, { label: 'Other', value: records.length - complete - pending - review, color: '#d5dde3' }].filter(d => d.value > 0);
  let cumulative = 0;
  const gradient = distribution.map(d => { const start = cumulative; cumulative += d.value / Math.max(records.length, 1) * 100; return `${d.color} ${start}% ${cumulative}%`; }).join(', ');
  return <div className="ws-page ws-dashboard">
    <PageHeading eyebrow={provider ? 'Provider management' : admin ? 'Administration' : 'Enrolment system'} title={title} description={provider ? 'Your network. Every provider. One clear view.' : admin ? 'A shared view of your team and daily operations.' : 'A clear view of your enrolments and what needs you next.'}>
      <Action data-testid="dashboard-export" onClick={() => exportCsv(records.map(r => ({ Reference: r.reference, Name: r.name, Status: r.status, Members: r.members })), 'operations-summary-sample.csv')}><Download size={16} />Export report</Action><Link className="ws-button ws-primary" to={`${base}?new=1`} data-testid="dashboard-new-enrolment"><Plus size={17} />{provider ? 'New provider' : 'New enrolment'}</Link>
    </PageHeading>
    <div className="ws-dashboard-subnav"><div className="ws-tabs"><Link className="active" to={pathname} data-testid="dashboard-tab-overview">Overview</Link><Link to={base} data-testid="dashboard-tab-queue">{provider ? 'Provider directory' : 'Corporate enrolment'}</Link><Link to={provider ? '/provider-masters/empanel' : '/enrolment-system/retail-inward'} data-testid="dashboard-tab-retail">{provider ? 'Empanelment' : 'Retail enrolment'}</Link></div><span className="ws-period"><CalendarDays size={14} />{new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' })}</span></div>
    <div className="ws-metrics-grid">{metrics.map((m, i) => <Link key={m.title} to={m.path} className={`ws-metric-card ${m.tone}`} data-testid={`dashboard-metric-${i}`}><div className="ws-metric-label"><span>{m.title}</span><m.icon size={18} /></div><div className="ws-metric-value" data-testid={`dashboard-metric-value-${i}`}>{m.value.toLocaleString('en-IN')}<span className="ws-sparkline" aria-hidden="true">{[12, 20, 15, 29, 22, 35, 30, 39].map((h, n) => <i key={n} style={{ height: h + (i % 2 ? -5 : 0) }} />)}</span></div><div className="ws-metric-note">{m.note}<ArrowUpRight size={14} /></div></Link>)}</div>
    <div className="ws-analytics-grid"><section className="ws-chart-section"><div className="ws-section-heading"><div><h2>{provider ? 'Network activity' : 'Enrolment activity'}</h2><p>Historical sample volumes</p></div><select data-testid="dashboard-period" aria-label="Activity period" value={period} onChange={e => setPeriod(e.target.value)}><option>Last 7 days</option><option>Last 30 days</option></select></div><div className="ws-chart-summary"><strong data-testid="activity-total">{chart.reduce((sum, d) => sum + d.completed + d.pending, 0).toLocaleString('en-IN')}</strong><span>{provider ? 'provider actions' : 'members processed'}</span><span className="ws-chart-legend"><i />Completed<i />Pending</span></div>
      <div className="ws-bar-chart" data-testid="activity-chart" role="img" aria-label={`Sample activity: ${chart.map(d => `${d.name}: ${d.completed} completed, ${d.pending} pending`).join('; ')}`}><ResponsiveContainer width="100%" height="100%"><BarChart data={chart} barSize={26} margin={{ top: 4, right: 5, bottom: 0, left: 5 }}><CartesianGrid vertical={false} stroke="#e9eef0" strokeDasharray="3 4" /><XAxis dataKey="name" axisLine={false} tickLine={false} tick={{ fill: '#77858d', fontSize: 11 }} dy={5} /><Tooltip cursor={{ fill: '#f3f7f7' }} contentStyle={{ border: '1px solid #e0e8e7', borderRadius: 6, fontFamily: 'IBM Plex Sans', fontSize: 12 }} /><Bar dataKey="completed" name="Completed" stackId="a" fill="#198f83" /><Bar dataKey="pending" name="Pending" stackId="a" fill="#bfe1db" radius={[4, 4, 0, 0]} /></BarChart></ResponsiveContainer></div></section>
      <section className="ws-distribution-section"><div className="ws-section-heading"><div><h2>{admin ? 'Team capacity' : 'Workload distribution'}</h2><p>{admin ? `${users.length} active directory users` : 'Current sample queue'}</p></div><Activity size={17} /></div><div className="ws-distribution-content"><div className="ws-donut" style={{ background: `conic-gradient(${gradient || '#e4e9eb 0% 100%'})` }} role="img" aria-label={`${complete} completed out of ${records.length} total`} data-testid="workload-chart"><div><strong>{records.length}</strong><span>Total records</span></div></div><div className="ws-distribution-legend">{distribution.map(d => <div key={d.label}><i style={{ background: d.color }} /><span>{d.label}</span><strong data-testid={`workload-${d.label.toLowerCase().replaceAll(/[^a-z]+/g, '-')}`}>{d.value}</strong></div>)}</div></div><Link className="ws-workload-link" to={admin ? '/user-management/users' : base} data-testid="dashboard-view-workload">{admin ? <><Users size={15} />Manage team</> : 'View workload'}<ArrowRight size={15} /></Link></section></div>
    <section className="ws-dashboard-queue"><div className="ws-section-heading"><div className="ws-queue-title"><h2>{provider ? 'Network directory' : 'Recent enrolments'}</h2><span className="ws-count-pill" data-testid="recent-total">{records.length}</span></div><SectionLink to={base} id="dashboard-view-all">View all records</SectionLink></div><div className="ws-table-scroll"><table className="ws-table ws-recent-table" data-testid="recent-records-table"><thead><tr><th>{provider ? 'Provider / code' : 'Corporate / policy'}</th><th className="ws-secondary-column">{provider ? 'Location' : 'Insurer'}</th><th className="ws-type-column">{provider ? 'Beds' : 'Members'}</th><th>Status</th><th>Assigned to</th><th /></tr></thead><tbody>{records.slice(0, 4).map(r => <tr key={r.id}><td className="ws-name-cell"><Link to={base} data-testid={`recent-record-${r.id}`}><span className={`ws-table-monogram tone-${r.name.length % 4}`}>{r.name.split(' ').slice(0, 2).map(s => s[0]).join('')}</span><span><strong>{r.name}</strong><small>{r.reference}</small></span></Link></td><td className="ws-secondary-column">{provider ? r.location : r.entity}</td><td className="ws-type-column ws-mono">{r.members.toLocaleString('en-IN')}</td><td><Badge status={r.status} id={`recent-status-${r.id}`} /></td><td className="ws-owner-cell"><span className="ws-owner-avatar">{r.owner.split(' ').map(n => n[0]).join('')}</span><span>{r.owner.split(' ')[0]}</span></td><td><Link to={base} aria-label={`View ${r.name}`} data-testid={`recent-view-${r.id}`}><ChevronRight size={16} /></Link></td></tr>)}</tbody></table></div></section>
  </div>;
}