import { useState } from 'react';
import { Save, RotateCcw, Monitor, Bell, UserRound, Check, ShieldCheck } from 'lucide-react';
import { toast } from 'sonner';
import { Action, PageHeading } from './components';
import { useKeycloak } from '@/app/contexts/keycloak/KeycloakProvider';

export default function SettingsPage() {
  const { userInfo } = useKeycloak();
  const [tab, setTab] = useState('Workspace');
  const [density, setDensity] = useState(localStorage.getItem('mdi-density') || 'comfortable');
  const [size, setSize] = useState(localStorage.getItem('mdi-page-size') || '6');
  const [saved, setSaved] = useState(false);
  const save = () => { try { localStorage.setItem('mdi-density', density); localStorage.setItem('mdi-page-size', size); document.documentElement.dataset.density = density; setSaved(true); toast.success('Workspace preferences saved in this browser.'); } catch { toast.error('Unable to save preferences. Browser storage is unavailable.'); } };
  return <div className="ws-page ws-settings"><PageHeading eyebrow="Administration" title="Settings" description="A workspace that works the way you do."><Action primary onClick={save} data-testid="settings-save"><Save size={16} />Save preferences</Action></PageHeading>
    <div className="ws-settings-layout"><nav className="ws-settings-nav" aria-label="Settings sections">{[{ label: 'Workspace', icon: Monitor }, { label: 'Account', icon: UserRound }, { label: 'Notifications', icon: Bell }].map(t => <button key={t.label} className={tab === t.label ? 'active' : ''} onClick={() => setTab(t.label)} data-testid={`settings-tab-${t.label.toLowerCase()}`}><t.icon size={17} />{t.label}</button>)}</nav>
      <section className="ws-settings-body">{tab === 'Workspace' ? <><h2>Workspace preferences</h2><p>Display preferences are saved to this browser.</p><div className="ws-setting-row"><div><h3>Table density</h3><p>Choose the spacing for your records.</p></div><div className="ws-density-options">{['comfortable', 'compact'].map(d => <button onClick={() => { setDensity(d); setSaved(false); }} className={density === d ? 'selected' : ''} aria-pressed={density === d} data-testid={`density-${d}`} key={d}><span className={`ws-density-preview ${d}`}>{[0, 1, 2].map(i => <i key={i} />)}</span><span>{d[0].toUpperCase() + d.slice(1)}{density === d && <Check size={13} />}</span></button>)}</div></div>
        <div className="ws-setting-row"><div><h3>Rows per page</h3><p>Default size for module directories.</p></div><select value={size} onChange={e => { setSize(e.target.value); setSaved(false); }} aria-label="Default rows per page" data-testid="settings-page-size">{[6, 10, 20].map(n => <option key={n}>{n}</option>)}</select></div>
        <div className="ws-setting-row"><div><h3>Workspace theme</h3><p>MD India · Precision Teal</p></div><div className="ws-colour-swatches" aria-label="Teal, charcoal and white theme"><i /><i /><i /><Check size={15} /></div></div><div className="ws-settings-actions"><Action data-testid="settings-reset" onClick={() => { setDensity('comfortable'); setSize('6'); setSaved(false); }}><RotateCcw size={14} />Reset to defaults</Action>{saved && <span className="ws-saved" role="status" data-testid="settings-saved"><Check size={15} />Preferences saved</span>}</div></> : tab === 'Account' ? <><h2>Account information</h2><div className="ws-info-note" data-testid="account-demo-notice">Identity is supplied by the existing authentication provider. Preview authentication is MOCKED.</div><dl className="ws-detail-list"><div><dt>Name</dt><dd data-testid="settings-account-name">{userInfo?.name || 'MD India Admin'}</dd></div><div><dt>Email</dt><dd data-testid="settings-account-email">{userInfo?.email || 'Not provided'}</dd></div><div><dt>Organisation</dt><dd>MD India Health Insurance TPA</dd></div></dl><p className="ws-account-note"><ShieldCheck size={18} />Contact your administrator to update your account or permissions.</p></> : <><h2>Notifications</h2><div className="ws-info-note" data-testid="settings-notification-notice">Live email and workflow notifications are not connected in this preview.</div><div className="ws-setting-row"><div><h3>Workflow notifications</h3><p>Managed by your organisation’s workflow service.</p></div><span className="ws-badge warning" data-testid="notification-service-status">Not connected</span></div></>}</section></div>
  </div>;
}