-- inward-service: initial reference and sample data (previously DataInitializer.java).
-- Runs once. ON CONFLICT DO NOTHING keeps rows that already exist untouched.

INSERT INTO public.inward_documents (file_metadata_id, content_type, created_at, document_type, download_url, file_name, file_size, inward_no, s3bucket_name, s3sub_bucket_name) VALUES ('DOC-001', 'application/pdf', '2026-10-03 15:23:57.103341', 'POLICY_SCHEDULE', '/v1/files/download/DOC-001', 'TCS_Policy_Schedule_2026.pdf', 1024500, 'INW-2026-1001', 'enrollment', 'corporate') ON CONFLICT DO NOTHING;
INSERT INTO public.inward_documents (file_metadata_id, content_type, created_at, document_type, download_url, file_name, file_size, inward_no, s3bucket_name, s3sub_bucket_name) VALUES ('DOC-002', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', '2026-10-03 15:23:57.103341', 'MEMBER_DATA', '/v1/files/download/DOC-002', 'TCS_Employees_Dependents_List.xlsx', 4502000, 'INW-2026-1001', 'enrollment', 'corporate') ON CONFLICT DO NOTHING;
INSERT INTO public.inwards (inward_no, created_at, department_id, entity_id, entity_type, inward_priority, inward_received_channel, inward_received_tpa_branch_id, inward_source_reference_no, s3bucket_name, s3sub_bucket_name, status) VALUES ('INW-2026-1001', '2026-10-03 15:23:56.823339', 'DEPT-ENROLL', 'CORP-201', 'CORPORATE', 'HIGH', 'EMAIL', 'BR-PUN', 'TCS/GHI/2026-27', 'enrollment', 'corporate', 'UNDER_PROCESS') ON CONFLICT DO NOTHING;
INSERT INTO public.inwards (inward_no, created_at, department_id, entity_id, entity_type, inward_priority, inward_received_channel, inward_received_tpa_branch_id, inward_source_reference_no, s3bucket_name, s3sub_bucket_name, status) VALUES ('INW-2026-1002', '2026-10-04 10:23:56.823339', 'DEPT-ENROLL', 'BRK-001', 'BROKER', 'MEDIUM', 'PORTAL', 'BR-MUM', 'MARSH/RELIANCE/009', 'enrollment', 'broker', 'RECEIVED') ON CONFLICT DO NOTHING;
INSERT INTO public.psu_file_metadata (id, file_name, insurer_name, member_data_found, policy_schedule_found, status, uploaded_at) VALUES ('PSU-001', 'NIA_TCS_POLICY_SCHEDULE_2026.xml', 'The New India Assurance Co. Ltd.', true, true, 'PENDING', '2026-10-04 12:23:57.121764') ON CONFLICT DO NOTHING;
INSERT INTO public.psu_file_metadata (id, file_name, insurer_name, member_data_found, policy_schedule_found, status, uploaded_at) VALUES ('PSU-002', 'UII_RELIANCE_MEMBERS_02.xml', 'United India Insurance Co. Ltd.', true, false, 'PENDING', '2026-10-04 13:23:57.121764') ON CONFLICT DO NOTHING;
