-- master-service: initial reference and sample data (previously DataInitializer.java).
-- Runs once. ON CONFLICT DO NOTHING keeps rows that already exist untouched.

INSERT INTO public.agents (agent_id, agent_name, contact_number, created_at, email, license_number, policy_agent_code, status) VALUES ('AGT-001', 'Ramesh Kumar Sharma', '9899112233', '2026-10-04 15:23:35.921475', 'ramesh.sharma@insurance.com', 'AGT/2026/01', 'AGT-RK-01', 'ACTIVE') ON CONFLICT DO NOTHING;
INSERT INTO public.agents (agent_id, agent_name, contact_number, created_at, email, license_number, policy_agent_code, status) VALUES ('AGT-002', 'Priya Suresh Verma', '9899334455', '2026-10-04 15:23:35.921475', 'priya.verma@insurance.com', 'AGT/2026/02', 'AGT-PV-02', 'ACTIVE') ON CONFLICT DO NOTHING;
INSERT INTO public.brokers (broker_id, broker_name, contact_number, created_at, email, license_number, policy_broker_code, status) VALUES ('BRK-001', 'Marsh India Insurance Brokers Pvt Ltd', '9820011223', '2026-10-04 15:23:35.911901', 'corporate@marsh.com', 'IRDA/DB/123', 'BRK-MARSH-01', 'ACTIVE') ON CONFLICT DO NOTHING;
INSERT INTO public.brokers (broker_id, broker_name, contact_number, created_at, email, license_number, policy_broker_code, status) VALUES ('BRK-002', 'Aon India Insurance Brokers Pvt Ltd', '9820044556', '2026-10-04 15:23:35.911901', 'corporate@aon.com', 'IRDA/DB/456', 'BRK-AON-02', 'ACTIVE') ON CONFLICT DO NOTHING;
INSERT INTO public.corporate_groups (corporate_group_id, created_at, group_code, group_name, status) VALUES ('GRP-101', '2026-10-04 15:23:35.886181', 'TATAGRP', 'Tata Enterprises', 'ACTIVE') ON CONFLICT DO NOTHING;
INSERT INTO public.corporate_groups (corporate_group_id, created_at, group_code, group_name, status) VALUES ('GRP-102', '2026-10-04 15:23:35.886181', 'RELGRP', 'Reliance Industries Group', 'ACTIVE') ON CONFLICT DO NOTHING;
INSERT INTO public.corporate_groups (corporate_group_id, created_at, group_code, group_name, status) VALUES ('GRP-103', '2026-10-04 15:23:35.886181', 'INFGRP', 'Infosys Group', 'ACTIVE') ON CONFLICT DO NOTHING;
INSERT INTO public.corporates (corporate_id, contact_person, corporate_group_id, corporate_gstin, corporate_hr_id, corporate_industry_sector_id, corporate_name, corporate_pan, created_at, email, mobile, status) VALUES ('CORP-201', 'Rohan Mehra', 'GRP-101', '27AABCT1234F1Z5', 'HR-TCS-01', 'IT_SERVICES', 'Tata Consultancy Services Ltd.', 'AABCT1234F', '2026-10-04 15:23:35.898375', 'rohan.m@tcs.com', '9876543210', 'ACTIVE') ON CONFLICT DO NOTHING;
INSERT INTO public.corporates (corporate_id, contact_person, corporate_group_id, corporate_gstin, corporate_hr_id, corporate_industry_sector_id, corporate_name, corporate_pan, created_at, email, mobile, status) VALUES ('CORP-202', 'Kavita Rao', 'GRP-101', '27AABCT5678G1Z2', 'HR-TM-01', 'AUTOMOTIVE', 'Tata Motors Ltd.', 'AABCT5678G', '2026-10-04 15:23:35.898375', 'kavita.r@tatamotors.com', '9876543211', 'ACTIVE') ON CONFLICT DO NOTHING;
INSERT INTO public.corporates (corporate_id, contact_person, corporate_group_id, corporate_gstin, corporate_hr_id, corporate_industry_sector_id, corporate_name, corporate_pan, created_at, email, mobile, status) VALUES ('CORP-203', 'Sameer Ambani', 'GRP-102', '27AABCR9999M1Z8', 'HR-JIO-01', 'TELECOM', 'Reliance Jio Infocomm Ltd.', 'AABCR9999M', '2026-10-04 15:23:35.898375', 'sameer.a@ril.com', '9876543212', 'ACTIVE') ON CONFLICT DO NOTHING;
INSERT INTO public.insurer_offices (office_id, address, city, insurer_id, office_code, office_name, office_type, parent_office_id, state) VALUES ('OFF-NIA-01', NULL, 'Mumbai', 'INS-001', '110000', 'NIA Mumbai Head Office', 'HEAD_OFFICE', NULL, 'Maharashtra') ON CONFLICT DO NOTHING;
INSERT INTO public.insurer_offices (office_id, address, city, insurer_id, office_code, office_name, office_type, parent_office_id, state) VALUES ('OFF-NIA-RO-01', NULL, 'Pune', 'INS-001', '112200', 'NIA Pune Regional Office', 'REGIONAL', NULL, 'Maharashtra') ON CONFLICT DO NOTHING;
INSERT INTO public.insurer_offices (office_id, address, city, insurer_id, office_code, office_name, office_type, parent_office_id, state) VALUES ('OFF-NIA-DO-01', NULL, 'Pune', 'INS-001', '112201', 'NIA Pune Divisional Office 1', 'DIVISIONAL', NULL, 'Maharashtra') ON CONFLICT DO NOTHING;
INSERT INTO public.insurer_offices (office_id, address, city, insurer_id, office_code, office_name, office_type, parent_office_id, state) VALUES ('OFF-NIA-UO-01', NULL, 'Pune', 'INS-001', '112202', 'NIA Pune Camp Underwriting Office', 'ISSUING', NULL, 'Maharashtra') ON CONFLICT DO NOTHING;
INSERT INTO public.insurer_offices (office_id, address, city, insurer_id, office_code, office_name, office_type, parent_office_id, state) VALUES ('OFF-UII-UO-01', NULL, 'Chennai', 'INS-002', '010200', 'UII Chennai Large Corporate Branch', 'ISSUING', NULL, 'Tamil Nadu') ON CONFLICT DO NOTHING;
INSERT INTO public.insurer_offices (office_id, address, city, insurer_id, office_code, office_name, office_type, parent_office_id, state) VALUES ('OFF-HDFC-UO-01', NULL, 'Mumbai', 'INS-005', 'HDFC-MUM-01', 'HDFC ERGO Corporate Underwriting Hub', 'ISSUING', NULL, 'Maharashtra') ON CONFLICT DO NOTHING;
INSERT INTO public.insurers (insurer_id, insurer_name, insurer_type, status) VALUES ('INS-001', 'The New India Assurance Co. Ltd.', 'PSU', 'ACTIVE') ON CONFLICT DO NOTHING;
INSERT INTO public.insurers (insurer_id, insurer_name, insurer_type, status) VALUES ('INS-002', 'United India Insurance Co. Ltd.', 'PSU', 'ACTIVE') ON CONFLICT DO NOTHING;
INSERT INTO public.insurers (insurer_id, insurer_name, insurer_type, status) VALUES ('INS-003', 'National Insurance Co. Ltd.', 'PSU', 'ACTIVE') ON CONFLICT DO NOTHING;
INSERT INTO public.insurers (insurer_id, insurer_name, insurer_type, status) VALUES ('INS-004', 'Oriental Insurance Co. Ltd.', 'PSU', 'ACTIVE') ON CONFLICT DO NOTHING;
INSERT INTO public.insurers (insurer_id, insurer_name, insurer_type, status) VALUES ('INS-005', 'HDFC ERGO General Insurance Co. Ltd.', 'PRIVATE', 'ACTIVE') ON CONFLICT DO NOTHING;
INSERT INTO public.insurers (insurer_id, insurer_name, insurer_type, status) VALUES ('INS-006', 'ICICI Lombard General Insurance Co. Ltd.', 'PRIVATE', 'ACTIVE') ON CONFLICT DO NOTHING;
INSERT INTO public.tpa_branches (branch_id, branch_code, branch_name, city, contact_person, email, phone, pin_code, state) VALUES ('BR-PUN', 'PUN01', 'Pune Central Servicing Hub', 'Pune', 'Suresh Kulkarni', 'pune.servicing@mdindia.com', '02026123456', '411001', 'Maharashtra') ON CONFLICT DO NOTHING;
INSERT INTO public.tpa_branches (branch_id, branch_code, branch_name, city, contact_person, email, phone, pin_code, state) VALUES ('BR-MUM', 'MUM01', 'Mumbai Corporate Branch', 'Mumbai', 'Rajesh Mehta', 'mumbai.servicing@mdindia.com', '02222123456', '400001', 'Maharashtra') ON CONFLICT DO NOTHING;
INSERT INTO public.tpa_branches (branch_id, branch_code, branch_name, city, contact_person, email, phone, pin_code, state) VALUES ('BR-DEL', 'DEL01', 'Delhi Regional Hub', 'New Delhi', 'Virender Singh', 'delhi.servicing@mdindia.com', '01123123456', '110001', 'Delhi') ON CONFLICT DO NOTHING;
INSERT INTO public.tpa_branches (branch_id, branch_code, branch_name, city, contact_person, email, phone, pin_code, state) VALUES ('BR-BLR', 'BLR01', 'Bengaluru Technology Hub', 'Bengaluru', 'Ananya Hegde', 'blr.servicing@mdindia.com', '08025123456', '560001', 'Karnataka') ON CONFLICT DO NOTHING;
INSERT INTO public.user_groups (group_name, description) VALUES ('Corporate-Enrolment-Processor', 'Makers for corporate policy enrolment') ON CONFLICT DO NOTHING;
INSERT INTO public.user_groups (group_name, description) VALUES ('Corporate-Enrolment-QC', 'Checkers / approvers for corporate policy enrolment') ON CONFLICT DO NOTHING;
INSERT INTO public.user_groups (group_name, description) VALUES ('Corporate-Endorsement-Processor', 'Makers for endorsement processing') ON CONFLICT DO NOTHING;
INSERT INTO public.user_groups (group_name, description) VALUES ('Corporate-Endorsement-QC', 'Checkers / approvers for endorsement processing') ON CONFLICT DO NOTHING;
INSERT INTO public.user_groups (group_name, description) VALUES ('Corporate-Enrolment-Admin', 'Supervisors and assignment admins') ON CONFLICT DO NOTHING;
INSERT INTO public.user_groups (group_name, description) VALUES ('Provider-Management', 'Makers and executives for provider network operations') ON CONFLICT DO NOTHING;
INSERT INTO public.user_groups (group_name, description) VALUES ('Provider-Management-Admin', 'Supervisors and admins for provider network') ON CONFLICT DO NOTHING;
INSERT INTO public.users (username, additional_roles, email, group_name, name, password_hash, role) VALUES ('ram.chaughule', 'super.admin,corporate_enrolment_admin,corporate_enrolment_qc,provider.admin,provider_user', 'ram.chaughule@mdindia.com', NULL, 'Ram Chaughule', 'pbkdf2$120000$a3R/cjR04zU92+46b7EjEA==$4DfyoX0GQoHHrLB/ciUULXyMDJb1BUTJ3+hFc+mmxSY=', 'enrolment_super_admin') ON CONFLICT DO NOTHING;
INSERT INTO public.users (username, additional_roles, email, group_name, name, password_hash, role) VALUES ('akshay.more', 'corporate_enrolment_qc', 'akshay.more@mdindia.com', 'Corporate-Enrolment-Processor', 'Akshay More', 'pbkdf2$120000$0w4vB/2ygP9QLucMfNSDnA==$2YxXQyiITNvTOkOc0RTdT1ft/OGbkbCWNMteaxrV6EY=', 'corporate_enrolment_processor') ON CONFLICT DO NOTHING;
INSERT INTO public.users (username, additional_roles, email, group_name, name, password_hash, role) VALUES ('kiran.patel', 'corporate_endorsement_qc,corporate_enrolment_admin', 'kiran.patel@mdindia.com', 'Corporate-Enrolment-QC', 'Kiran Patel', 'pbkdf2$120000$TQW4+1vihhaZr0slJ6AgsQ==$MYzbkyZKrfvaz9Th4azV5363JNaCIL2f0YYhCzHATdA=', 'corporate_enrolment_qc') ON CONFLICT DO NOTHING;
INSERT INTO public.users (username, additional_roles, email, group_name, name, password_hash, role) VALUES ('provider.admin', 'super.admin,provider.admin,admin,checker,maker1', 'provider.admin@mdindia.com', 'Provider-Management-Admin', 'Provider Network Admin', 'pbkdf2$120000$31ErLa7kx6pyasjK2uQ9hw==$yPdI+J/5fuiGBjrj0akk717c2w736CyNvq4tERpz9E8=', 'provider.admin') ON CONFLICT DO NOTHING;
INSERT INTO public.users (username, additional_roles, email, group_name, name, password_hash, role) VALUES ('provider.user', 'provider.admin,maker1,maker2', 'provider.user@mdindia.com', 'Provider-Management', 'Provider Operations Executive', 'pbkdf2$120000$31ErLa7kx6pyasjK2uQ9hw==$yPdI+J/5fuiGBjrj0akk717c2w736CyNvq4tERpz9E8=', 'provider_user') ON CONFLICT DO NOTHING;

