/** Field keys for `GET v1/files/inwards` (document-upload-management-service). */
export const BULK_IC_MAPPING_INWARD_API_KEYS = {
  inwardNo: "inwardNo",
  inwardReceivedAt: "inwardReceivedAt",
  inwardSourceReferenceNo: "inwardSourceReferenceNo",
  sourceEntityName: "sourceEntityName",
  s3SubBucketName: "s3SubBucketName",
  documentType: "documentType",
  status: "status",
  originalFileName: "originalFileName",
  insurerName: "insurerName",
  corporateName: "corporateLegalName",
  createdBy: "createdBy",
  recordStatus: "recordStatus",
  inwardSourceEntityId: "inwardSourceEntityId",
  inwardSourceEntityType: "inwardSourceEntityType",
  inwardReceivedTpaBranchId: "inwardReceivedTpaBranchId",
  departmentId: "departmentId",
  parentInwardNo: "parentInwardNo",
  createdAt: "createdAt",
  policyNo: "policyNo",
  enrollmentType: "enrollmentType",
  fileName: "fileName",
} as const;
