/** Field keys for GET `/v1/provider-restriction/{providerRestrictionId}`. */
export const PROVIDER_RESTRICTION_KEYS = {
  providerRestrictionId: "providerRestrictionId",
  providerId: "providerId",
  insurerId: "insurerId",
  insurerName: "insurerName",
  corporateId: "corporateId",
  corporateName: "corporateName",
  corporateNames: "corporateNames",
  providerRestrictionType: "providerRestrictionType",
  providerRestrictionApplicableFor: "providerRestrictionApplicableFor",
  providerRestrictionEffectiveFrom: "providerRestrictionEffectiveFrom",
  providerRestrictionEffectiveTo: "providerRestrictionEffectiveTo",
  providerRestrictionLevel: "providerRestrictionLevel",
  providerRestrictionReasonCode: "providerRestrictionReasonCode",
  providerRestrictionReasonDescription: "providerRestrictionReasonDescription",
  remark: "remark",
  inwardNo: "inwardNo",
  supportingFileMetadataId: "supportingFileMetadataId",
  corporateIds: "corporateIds",
  policyIds: "policyIds",
  insurerOfficeIds: "insurerOfficeIds",
  insurerOfficeName: "insurerOfficeName",
  policyNumber: "policyNumber",
  policyNumbers: "policyNumbers",
  ccnNumbers: "ccnNumbers",
  emergencyExceptionAllowedFlag: "emergencyExceptionAllowedFlag",
  investigationRequiredFlag: "investigationRequiredFlag",
  providerRestrictionStatus: "providerRestrictionStatus",
} as const;

/** Query params for `GET /v1/provider-restriction` list. */
export const PROVIDER_RESTRICTION_LIST_FILTER_KEYS = {
  providerId: "providerId",
  insurerId: "insurerId",
  corporateId: "corporateId",
  policyId: "policyId",
  tpaId: "tpaId",
  providerRestrictionZoneId: "providerRestrictionZoneId",
  providerRestrictionType: "providerRestrictionType",
  providerRestrictionStatus: "providerRestrictionStatus",
  page: "page",
  size: "size",
} as const;
