// src/services/mockEnrollmentData.ts

export const MOCK_CORPORATE_GROUPS = [
  {
    corporateGroupId: "CG-001",
    groupCode: "TATA-GRP",
    groupName: "Tata Sons Group",
    legalName: "Tata Sons Private Limited",
    cin: "U99999MH1917PLC000478",
    pan: "AAACT1234F",
    gstin: "27AAACT1234F1Z5",
    websiteUrl: "https://www.tata.com",
    status: "ACTIVE",
    effectiveFrom: "2020-01-01",
    effectiveTo: null,
    notes: "Premier corporate conglomerate",
    createdAt: "2020-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
    lastModifications: null,
  },
  {
    corporateGroupId: "CG-002",
    groupCode: "RIL-GRP",
    groupName: "Reliance Group",
    legalName: "Reliance Industries Group",
    cin: "L17110MH1973PLC019786",
    pan: "AAACR1234D",
    gstin: "27AAACR1234D1Z2",
    websiteUrl: "https://www.ril.com",
    status: "ACTIVE",
    effectiveFrom: "2021-04-01",
    effectiveTo: null,
    notes: "Energy and telecom conglomerate",
    createdAt: "2021-04-01T00:00:00Z",
    updatedAt: "2024-02-15T00:00:00Z",
    lastModifications: null,
  },
  {
    corporateGroupId: "CG-003",
    groupCode: "INFY-GRP",
    groupName: "Infosys Group",
    legalName: "Infosys Limited Group",
    cin: "L85110KA1981PLC013115",
    pan: "AAACI1234G",
    gstin: "29AAACI1234G1Z9",
    websiteUrl: "https://www.infosys.com",
    status: "ACTIVE",
    effectiveFrom: "2021-06-01",
    effectiveTo: null,
    notes: "Global technology consulting leader",
    createdAt: "2021-06-01T00:00:00Z",
    updatedAt: "2024-03-10T00:00:00Z",
    lastModifications: null,
  },
  {
    corporateGroupId: "CG-004",
    groupCode: "M&M-GRP",
    groupName: "Mahindra Group",
    legalName: "Mahindra & Mahindra Group",
    cin: "L65990MH1945PLC004558",
    pan: "AAACM1234H",
    gstin: "27AAACM1234H1Z6",
    websiteUrl: "https://www.mahindra.com",
    status: "ACTIVE",
    effectiveFrom: "2022-01-01",
    effectiveTo: null,
    notes: "Automotive and farm equipment leader",
    createdAt: "2022-01-01T00:00:00Z",
    updatedAt: "2024-04-01T00:00:00Z",
    lastModifications: null,
  },
];

export const MOCK_CORPORATES = [
  {
    corporateId: "CORP001",
    corporateCode: "TCS-CORP",
    legalName: "Tata Consultancy Services Limited",
    tradeName: "TCS",
    corporateType: "PUBLIC_LIMITED",
    corporateGroupId: "CG-001",
    corporateGroupName: "Tata Sons Group",
    pan: "AAACT2345K",
    gstin: "27AAACT2345K1Z8",
    cin: "L22210MH1995PLC084781",
    industrySectorCode: "IT_SERVICES",
    sizeBand: "LARGE",
    employeeCount: 45000,
    billingCycle: "MONTHLY",
    riskTier: "LOW",
    websiteUrl: "https://www.tcs.com",
    tpaRelationshipType: "EXCLUSIVE",
    onBoardedDate: "2021-04-01",
    status: "ACTIVE",
    effectiveFrom: "2021-04-01",
    effectiveTo: "2030-03-31",
    contactEmail: ["benefits@tcs.com", "insurance.desk@tcs.com"],
    contactPhone: ["+91 22 6778 9999", "+91 22 6778 9000"],
    notes: "Core IT Corporate client with pan-India floater cover",
    address: {
      address: "TCS House, Raveline Street, Fort",
      locality: "Fort",
      landmark: "Near CST Railway Station",
      villageTown: "Mumbai",
      city: "Mumbai",
      district: "Mumbai City",
      stateName: "Maharashtra",
      stateCode: "MH",
      postalCode: "400001",
      validFrom: "2021-04-01",
      validTo: "2030-03-31",
      tags: ["HEAD_OFFICE"],
      extendedAttributes: {},
    },
    createdAt: "2021-04-01T09:00:00Z",
    updatedAt: "2024-05-15T12:00:00Z",
  },
  {
    corporateId: "CORP002",
    corporateCode: "INFY-CORP",
    legalName: "Infosys Technologies Private Limited",
    tradeName: "Infosys",
    corporateType: "PUBLIC_LIMITED",
    corporateGroupId: "CG-003",
    corporateGroupName: "Infosys Group",
    pan: "AAACI9876L",
    gstin: "29AAACI9876L1Z4",
    cin: "L85110KA1981PLC013115",
    industrySectorCode: "IT_SERVICES",
    sizeBand: "LARGE",
    employeeCount: 32000,
    billingCycle: "QUARTERLY",
    riskTier: "LOW",
    websiteUrl: "https://www.infosys.com",
    tpaRelationshipType: "PREFERRED",
    onBoardedDate: "2021-06-01",
    status: "ACTIVE",
    effectiveFrom: "2021-06-01",
    effectiveTo: "2029-05-31",
    contactEmail: ["hr.insurance@infosys.com"],
    contactPhone: ["+91 80 2852 0261"],
    notes: "Technology major covered with comprehensive family floater",
    address: {
      address: "Plot No. 44, Electronic City, Hosur Road",
      locality: "Electronic City",
      landmark: "Phase 1",
      villageTown: "Bengaluru",
      city: "Bengaluru",
      district: "Bengaluru Urban",
      stateName: "Karnataka",
      stateCode: "KA",
      postalCode: "560100",
      validFrom: "2021-06-01",
      validTo: "2029-05-31",
      tags: ["HEAD_OFFICE"],
      extendedAttributes: {},
    },
    createdAt: "2021-06-01T10:00:00Z",
    updatedAt: "2024-04-10T11:00:00Z",
  },
  {
    corporateId: "CORP003",
    corporateCode: "RIL-CORP",
    legalName: "Reliance Industries Limited",
    tradeName: "RIL",
    corporateType: "PUBLIC_LIMITED",
    corporateGroupId: "CG-002",
    corporateGroupName: "Reliance Group",
    pan: "AAACR4567M",
    gstin: "27AAACR4567M1Z1",
    cin: "L17110MH1973PLC019786",
    industrySectorCode: "BFSI",
    sizeBand: "ENTERPRISE",
    employeeCount: 28000,
    billingCycle: "MONTHLY",
    riskTier: "MEDIUM",
    websiteUrl: "https://www.ril.com",
    tpaRelationshipType: "EXCLUSIVE",
    onBoardedDate: "2022-01-15",
    status: "ACTIVE",
    effectiveFrom: "2022-01-15",
    effectiveTo: "2031-01-14",
    contactEmail: ["corporate.benefits@ril.com"],
    contactPhone: ["+91 22 3555 5000"],
    notes: "Diversified conglomerate covering corporate & retail health",
    address: {
      address: "Maker Chambers IV, 222 Nariman Point",
      locality: "Nariman Point",
      landmark: "Opposite CR2 Mall",
      villageTown: "Mumbai",
      city: "Mumbai",
      district: "Mumbai City",
      stateName: "Maharashtra",
      stateCode: "MH",
      postalCode: "400021",
      validFrom: "2022-01-15",
      validTo: "2031-01-14",
      tags: ["HEAD_OFFICE"],
      extendedAttributes: {},
    },
    createdAt: "2022-01-15T08:30:00Z",
    updatedAt: "2024-06-01T14:20:00Z",
  },
  {
    corporateId: "CORP004",
    corporateCode: "WIP-CORP",
    legalName: "Wipro Enterprises Private Limited",
    tradeName: "Wipro",
    corporateType: "PRIVATE_LIMITED",
    corporateGroupId: "CG-003",
    corporateGroupName: "Infosys Group",
    pan: "AAACW3456P",
    gstin: "29AAACW3456P1Z7",
    cin: "U15141KA2010PTC054808",
    industrySectorCode: "AUTO_MFG",
    sizeBand: "MEDIUM",
    employeeCount: 19000,
    billingCycle: "MONTHLY",
    riskTier: "LOW",
    websiteUrl: "https://www.wipro.com",
    tpaRelationshipType: "PREFERRED",
    onBoardedDate: "2022-08-01",
    status: "ACTIVE",
    effectiveFrom: "2022-08-01",
    effectiveTo: "2028-07-31",
    contactEmail: ["benefits@wipro.com"],
    contactPhone: ["+91 80 2844 0011"],
    notes: "Global IT services and consulting provider",
    address: {
      address: "Doddakannelli, Sarjapur Road",
      locality: "Sarjapur",
      landmark: "Wipro Campus",
      villageTown: "Bengaluru",
      city: "Bengaluru",
      district: "Bengaluru Urban",
      stateName: "Karnataka",
      stateCode: "KA",
      postalCode: "560035",
      validFrom: "2022-08-01",
      validTo: "2028-07-31",
      tags: ["HEAD_OFFICE"],
      extendedAttributes: {},
    },
    createdAt: "2022-08-01T11:00:00Z",
    updatedAt: "2024-03-25T16:00:00Z",
  },
  {
    corporateId: "CORP005",
    corporateCode: "MMFS-CORP",
    legalName: "Mahindra & Mahindra Financial Services Limited",
    tradeName: "Mahindra Finance",
    corporateType: "PUBLIC_LIMITED",
    corporateGroupId: "CG-004",
    corporateGroupName: "Mahindra Group",
    pan: "AAACM5678Q",
    gstin: "27AAACM5678Q1Z3",
    cin: "L65921MH1991PLC059642",
    industrySectorCode: "BFSI",
    sizeBand: "LARGE",
    employeeCount: 24000,
    billingCycle: "MONTHLY",
    riskTier: "LOW",
    websiteUrl: "https://www.mahindrafinance.com",
    tpaRelationshipType: "EXCLUSIVE",
    onBoardedDate: "2023-01-01",
    status: "ACTIVE",
    effectiveFrom: "2023-01-01",
    effectiveTo: "2030-12-31",
    contactEmail: ["mediclaim@mahindrafinance.com"],
    contactPhone: ["+91 22 6652 6000"],
    notes: "Non-banking financial company catering to rural & semi-urban India",
    address: {
      address: "Sadhana House, 2nd Floor, 570 P.B. Marg, Worli",
      locality: "Worli",
      landmark: "Behind Mahindra Towers",
      villageTown: "Mumbai",
      city: "Mumbai",
      district: "Mumbai City",
      stateName: "Maharashtra",
      stateCode: "MH",
      postalCode: "400018",
      validFrom: "2023-01-01",
      validTo: "2030-12-31",
      tags: ["HEAD_OFFICE"],
      extendedAttributes: {},
    },
    createdAt: "2023-01-01T09:00:00Z",
    updatedAt: "2024-02-18T10:30:00Z",
  },
];

export const MOCK_BROKERS = [
  {
    brokerId: "BRK001",
    brokerCode: "BRK-MARSH-01",
    legalName: "Marsh India Insurance Brokers Pvt Ltd",
    tradeName: "Marsh McLennan India",
    irdaBrokerCode: "IRDA/DB/084/02",
    brokerType: "COMPOSITE",
    licenseNumber: "LIC-IRDA-BRK-2021-084",
    licenseStatus: "VALID",
    licenseValidFrom: "2021-01-01",
    licenseValidTo: "2027-12-31",
    pan: "AABCM1122D",
    gstin: "27AABCM1122D1Z3",
    cin: "U66010MH2002PTC138248",
    headOfficeCity: "Mumbai",
    websiteUrl: "https://www.marsh.com",
    status: "ACTIVE",
    effectiveFrom: "2021-01-01",
    effectiveTo: "2027-12-31",
    contactEmail: ["indiabrokerage@marsh.com"],
    contactPhone: ["022-66585858"],
    address: {
      brokerAddressId: "BADDR-001",
      address: "1201-02, Tower 2, One World Center, Jupiter Mills, Lower Parel",
      locality: "Lower Parel",
      landmark: "One World Center",
      villageTown: "Mumbai",
      city: "Mumbai",
      district: "Mumbai",
      stateName: "Maharashtra",
      stateCode: "MH",
      postalCode: "400013",
      countryCode: "IND",
      validFrom: "2021-01-01",
      validTo: "2027-12-31",
      tags: ["HEAD_OFFICE"],
      extendedAttributes: {},
      addressStatus: "ACTIVE",
    },
    createdAt: "2021-01-01T00:00:00Z",
    updatedAt: "2024-01-10T00:00:00Z",
  },
  {
    brokerId: "BRK002",
    brokerCode: "BRK-AON-02",
    legalName: "Aon India Insurance Brokers Private Limited",
    tradeName: "Aon India",
    irdaBrokerCode: "IRDA/DB/156/03",
    brokerType: "COMPOSITE",
    licenseNumber: "LIC-IRDA-BRK-2022-156",
    licenseStatus: "VALID",
    licenseValidFrom: "2022-04-01",
    licenseValidTo: "2028-03-31",
    pan: "AABCA9988E",
    gstin: "27AABCA9988E1Z9",
    cin: "U66030MH2002PTC137889",
    headOfficeCity: "Mumbai",
    websiteUrl: "https://www.aon.com",
    status: "ACTIVE",
    effectiveFrom: "2022-04-01",
    effectiveTo: "2028-03-31",
    contactEmail: ["corporate.solutions@aon.com"],
    contactPhone: ["022-42125555"],
    address: {
      brokerAddressId: "BADDR-002",
      address: "Equinox Business Park, Tower 1, BKC LBS Marg, Kurla West",
      locality: "Kurla West",
      landmark: "Equinox Business Park",
      villageTown: "Mumbai",
      city: "Mumbai",
      district: "Mumbai",
      stateName: "Maharashtra",
      stateCode: "MH",
      postalCode: "400070",
      countryCode: "IND",
      validFrom: "2022-04-01",
      validTo: "2028-03-31",
      tags: ["HEAD_OFFICE"],
      extendedAttributes: {},
      addressStatus: "ACTIVE",
    },
    createdAt: "2022-04-01T00:00:00Z",
    updatedAt: "2024-02-15T00:00:00Z",
  },
  {
    brokerId: "BRK003",
    brokerCode: "BRK-WTW-03",
    legalName: "Willis Towers Watson India Insurance Brokers Pvt Ltd",
    tradeName: "WTW India",
    irdaBrokerCode: "IRDA/DB/170/03",
    brokerType: "COMPOSITE",
    licenseNumber: "LIC-IRDA-BRK-2023-170",
    licenseStatus: "VALID",
    licenseValidFrom: "2023-01-01",
    licenseValidTo: "2029-12-31",
    pan: "AABCW4433F",
    gstin: "27AABCW4433F1Z1",
    cin: "U66010MH2003PTC140228",
    headOfficeCity: "Gurugram",
    websiteUrl: "https://www.wtwco.com",
    status: "ACTIVE",
    effectiveFrom: "2023-01-01",
    effectiveTo: "2029-12-31",
    contactEmail: ["india.brokerage@wtwco.com"],
    contactPhone: ["0124-4322800"],
    address: {
      brokerAddressId: "BADDR-003",
      address: "DLF Cyber City, Building 7A, 4th Floor, Sector 25A",
      locality: "DLF Cyber City",
      landmark: "Building 7A",
      villageTown: "Gurugram",
      city: "Gurugram",
      district: "Gurugram",
      stateName: "Haryana",
      stateCode: "HR",
      postalCode: "122002",
      countryCode: "IND",
      validFrom: "2023-01-01",
      validTo: "2029-12-31",
      tags: ["HEAD_OFFICE"],
      extendedAttributes: {},
      addressStatus: "ACTIVE",
    },
    createdAt: "2023-01-01T00:00:00Z",
    updatedAt: "2024-03-20T00:00:00Z",
  },
];

export const MOCK_AGENTS = [
  {
    agentId: "AGT001",
    legalName: "Rajesh Sharma Insurance Agency",
    tradeName: "Sharma Insurance Services",
    agentType: "INDIVIDUAL",
    agentCategory: "COMPOSITE",
    irdaAgentCode: "AGT-NIA-88910",
    status: "ACTIVE",
    notes: "Specialized in corporate GMC and retail mediclaim policies",
    licenseValidFrom: "2022-04-01",
    licenseValidTo: "2028-03-31",
    contactEmail: ["rajesh.sharma@insuranceagent.in"],
    contactPhone: ["+91 98200 12345"],
    createdAt: "2022-04-01T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
  },
  {
    agentId: "AGT002",
    legalName: "Sunita Deshmukh Associates",
    tradeName: "Deshmukh Financial Advisory",
    agentType: "CORPORATE",
    agentCategory: "HEALTH",
    irdaAgentCode: "AGT-NIC-77123",
    status: "ACTIVE",
    notes: "Top performer for National Insurance corporate portfolio",
    licenseValidFrom: "2023-01-01",
    licenseValidTo: "2029-12-31",
    contactEmail: ["sunita@deshmukhfinancial.com"],
    contactPhone: ["+91 98190 54321"],
    createdAt: "2023-01-01T00:00:00Z",
    updatedAt: "2024-02-10T00:00:00Z",
  },
];

export const MOCK_INDUSTRY_SECTORS = [
  { label: "Information Technology & Software", value: "IT_SERVICES" },
  { label: "Banking, Financial Services & Insurance (BFSI)", value: "BFSI" },
  { label: "Automobile & Manufacturing", value: "AUTO_MFG" },
  { label: "Pharmaceuticals & Healthcare", value: "PHARMA" },
  { label: "Retail & E-Commerce", value: "RETAIL" },
  { label: "Telecommunications & Infrastructure", value: "TELECOM" },
  { label: "Fast Moving Consumer Goods (FMCG)", value: "FMCG" },
];

export const MOCK_POLICIES = [
  {
    id: "POL001",
    policyId: "POL001",
    policyNumber: "POL/2024/00912",
    policy: {
      policyId: "POL001",
      policyNumber: "POL/2024/00912",
      policyProposerName: "Tata Consultancy Services Limited",
      corporateName: "Tata Consultancy Services Limited",
      corporateId: "CORP001",
      insurerName: "National Insurance Company Limited",
      insurerId: "INS001",
      insurerBranchName: "Mumbai Divisional Office 1",
      policyStartDate: "2024-04-01T00:00:00Z",
      policyEndDate: "2025-03-31T23:59:59Z",
      policyCoverageStructureType: "FLOATER",
      policyType: "CORPORATE_GMC",
      brokerName: "Marsh India Insurance Brokers Pvt Ltd",
      brokerId: "BRK001",
      masterProductName: "National Parivar Mediclaim Plus Policy",
      masterProductId: "PROD001",
      policyStatus: "ACTIVE",
      tpaServicingBranchName: "MD India Pune Central Head Office",
      tpaBranchId: "BR001",
      policySumInsured: 500000,
      totalLivesInsured: 1250,
      currency: "INR",
    },
    premiums: [
      {
        premiumId: "PRM-001",
        premiumGrossAmount: 14500000,
        premiumTaxAmount: 2610000,
        netPremium: 17110000,
        installmentType: "ANNUAL",
        paymentStatus: "PAID",
      },
    ],
    contacts: [
      {
        contactPersonName: "Amitabh Verma",
        designation: "Head of Corporate Benefits",
        email: "averma@tcs.com",
        phone: "+91 98201 54321",
      },
    ],
  },
  {
    id: "POL002",
    policyId: "POL002",
    policyNumber: "POL/2024/00885",
    policy: {
      policyId: "POL002",
      policyNumber: "POL/2024/00885",
      policyProposerName: "Infosys Technologies Private Limited",
      corporateName: "Infosys Technologies Private Limited",
      corporateId: "CORP002",
      insurerName: "The New India Assurance Co. Ltd.",
      insurerId: "INS002",
      insurerBranchName: "Bengaluru Regional Office",
      policyStartDate: "2024-06-01T00:00:00Z",
      policyEndDate: "2025-05-31T23:59:59Z",
      policyCoverageStructureType: "FLOATER",
      policyType: "CORPORATE_GMC",
      brokerName: "Aon India Insurance Brokers Private Limited",
      brokerId: "BRK002",
      masterProductName: "New India Premier Mediclaim Policy",
      masterProductId: "PROD002",
      policyStatus: "ACTIVE",
      tpaServicingBranchName: "MD India Bengaluru Branch",
      tpaBranchId: "BR004",
      policySumInsured: 750000,
      totalLivesInsured: 890,
      currency: "INR",
    },
    premiums: [
      {
        premiumId: "PRM-002",
        premiumGrossAmount: 11200000,
        premiumTaxAmount: 2016000,
        netPremium: 13216000,
        installmentType: "ANNUAL",
        paymentStatus: "PAID",
      },
    ],
    contacts: [
      {
        contactPersonName: "Radha Krishnan",
        designation: "VP - Human Resources",
        email: "radha.k@infosys.com",
        phone: "+91 98450 67890",
      },
    ],
  },
  {
    id: "POL003",
    policyId: "POL003",
    policyNumber: "POL/2024/00750",
    policy: {
      policyId: "POL003",
      policyNumber: "POL/2024/00750",
      policyProposerName: "Reliance Industries Limited",
      corporateName: "Reliance Industries Limited",
      corporateId: "CORP003",
      insurerName: "Star Health and Allied Insurance Co. Ltd.",
      insurerId: "INS005",
      insurerBranchName: "Mumbai Central Branch",
      policyStartDate: "2024-01-01T00:00:00Z",
      policyEndDate: "2024-12-31T23:59:59Z",
      policyCoverageStructureType: "NON_FLOATER",
      policyType: "GROUP_HEALTH_TOPUP",
      brokerName: "Willis Towers Watson India Insurance Brokers",
      brokerId: "BRK003",
      masterProductName: "Star Comprehensive Health Insurance Plan",
      masterProductId: "PROD003",
      policyStatus: "ACTIVE",
      tpaServicingBranchName: "MD India Mumbai Regional Office",
      tpaBranchId: "BR002",
      policySumInsured: 1000000,
      totalLivesInsured: 640,
      currency: "INR",
    },
    premiums: [
      {
        premiumId: "PRM-003",
        premiumGrossAmount: 9800000,
        premiumTaxAmount: 1764000,
        netPremium: 11564000,
        installmentType: "ANNUAL",
        paymentStatus: "PAID",
      },
    ],
    contacts: [
      {
        contactPersonName: "Sanjay Singhal",
        designation: "General Manager Benefits",
        email: "sanjay.singhal@ril.com",
        phone: "+91 98210 33445",
      },
    ],
  },
];

export const MOCK_INWARDS = [
  {
    id: "INW-2024-00101",
    inwardNo: "INW-2024-00101",
    policyNo: "POL/2024/00912",
    createdAt: "2024-10-01T09:30:00Z",
    receivedAt: "2024-10-01T09:30:00Z",
    enrollmentType: "FRESH_POLICY_ENROLLMENT",
    category: "CORPORATE_ENROLMENT",
    subCategory: "FRESH_POLICY",
    appName: "ENROLLMENT_PORTAL",
    receivedChannel: "EMAIL",
    entityType: "CORPORATE",
    recordStatus: "ACTIVE",
    documentType: "POLICY_SCHEDULE",
    policyRecordType: "CORPORATE",
    insurerName: "National Insurance Company Limited",
    insurerId: "INS001",
    corporateName: "Tata Consultancy Services Limited",
    corporateId: "CORP001",
    status: "PROCESSOR_PENDING",
    latestRemark: "Roster submitted by broker. Initial OCR parsing completed with 98% accuracy.",
  },
  {
    id: "INW-2024-00102",
    inwardNo: "INW-2024-00102",
    policyNo: "POL/2024/00885",
    createdAt: "2024-10-02T11:15:00Z",
    receivedAt: "2024-10-02T11:15:00Z",
    enrollmentType: "FRESH_POLICY_ENROLLMENT",
    category: "CORPORATE_ENROLMENT",
    subCategory: "MEMBER_ROSTER",
    appName: "ENROLLMENT_PORTAL",
    receivedChannel: "SFTP_AUTO",
    entityType: "CORPORATE",
    recordStatus: "ACTIVE",
    documentType: "EMPLOYEE_ROSTER",
    policyRecordType: "CORPORATE",
    insurerName: "The New India Assurance Co. Ltd.",
    insurerId: "INS002",
    corporateName: "Infosys Technologies Private Limited",
    corporateId: "CORP002",
    status: "QC_PENDING",
    latestRemark: "Processor verified member data. Transferred to QC team for final sign-off.",
  },
  {
    id: "INW-2024-00103",
    inwardNo: "INW-2024-00103",
    policyNo: "POL/2024/00750",
    createdAt: "2024-10-03T14:45:00Z",
    receivedAt: "2024-10-03T14:45:00Z",
    enrollmentType: "FRESH_POLICY_ENDORSEMENT",
    category: "ENDORSEMENT",
    subCategory: "ADDITION",
    appName: "ENROLLMENT_PORTAL",
    receivedChannel: "HR_PORTAL",
    entityType: "CORPORATE",
    recordStatus: "ACTIVE",
    documentType: "EMPLOYEE_ROSTER",
    policyRecordType: "CORPORATE",
    insurerName: "Star Health and Allied Insurance Co. Ltd.",
    insurerId: "INS005",
    corporateName: "Reliance Industries Limited",
    corporateId: "CORP003",
    status: "UNDER_PROCESS",
    latestRemark: "Mid-term endorsement batch with 65 new joinees. Staging validation in progress.",
  },
  {
    id: "INW-2024-00104",
    inwardNo: "INW-2024-00104",
    policyNo: "POL/2024/00640",
    createdAt: "2024-09-28T16:00:00Z",
    receivedAt: "2024-09-28T16:00:00Z",
    enrollmentType: "FRESH_POLICY_ENROLLMENT",
    category: "CORPORATE_ENROLMENT",
    subCategory: "FRESH_POLICY",
    appName: "ENROLLMENT_PORTAL",
    receivedChannel: "EMAIL",
    entityType: "CORPORATE",
    recordStatus: "ACTIVE",
    documentType: "POLICY_SCHEDULE",
    policyRecordType: "CORPORATE",
    insurerName: "National Insurance Company Limited",
    insurerId: "INS001",
    corporateName: "Wipro Enterprises Private Limited",
    corporateId: "CORP004",
    status: "COMPLETED",
    latestRemark: "Policy enrolled and all 1,195 e-cards dispatched via automated email.",
  },
  {
    id: "INW-2024-00105",
    inwardNo: "INW-2024-00105",
    policyNo: "POL/2024/00520",
    createdAt: "2024-10-04T10:00:00Z",
    receivedAt: "2024-10-04T10:00:00Z",
    enrollmentType: "FRESH_POLICY_ENROLLMENT",
    category: "CORPORATE_ENROLMENT",
    subCategory: "MEMBER_ROSTER",
    appName: "ENROLLMENT_PORTAL",
    receivedChannel: "PORTAL_UPLOAD",
    entityType: "CORPORATE",
    recordStatus: "ACTIVE",
    documentType: "EMPLOYEE_ROSTER",
    policyRecordType: "CORPORATE",
    insurerName: "United India Insurance Company Limited",
    insurerId: "INS004",
    corporateName: "Mahindra & Mahindra Financial Services Limited",
    corporateId: "CORP005",
    status: "ONBOARDING_PENDING",
    latestRemark: "Underwriter approval required for sum insured ceiling enhancement.",
  },
  {
    id: "INW-2024-00106",
    inwardNo: "INW-2024-00106",
    policyNo: "POL/2024/00410",
    createdAt: "2024-09-25T12:30:00Z",
    receivedAt: "2024-09-25T12:30:00Z",
    enrollmentType: "FRESH_POLICY_ENDORSEMENT",
    category: "ENDORSEMENT",
    subCategory: "DELETION",
    appName: "ENROLLMENT_PORTAL",
    receivedChannel: "EMAIL",
    entityType: "CORPORATE",
    recordStatus: "ACTIVE",
    documentType: "EMPLOYEE_ROSTER",
    policyRecordType: "CORPORATE",
    insurerName: "ICICI Lombard General Insurance Co. Ltd.",
    insurerId: "INS006",
    corporateName: "Tata Consultancy Services Limited",
    corporateId: "CORP001",
    status: "REJECTED_INWARD",
    latestRemark: "Inward rejected: CD balance insufficient to process requested deletion refund.",
  },
];

export const MOCK_STAGE_COUNTS_FOR_ALL_USERS = {
  total: 42,
  pending: 15,
  rejected: 3,
  completed: 24,
};

export const MOCK_STATUS_COUNT = {
  ALL: 42,
  PROCESSOR_PENDING: 15,
  UNDER_PROCESS: 8,
  QC_PENDING: 9,
  ONBOARDING_PENDING: 6,
  COMPLETED: 24,
  REJECTED_INWARD: 3,
};

export const MOCK_MEMBER_STATISTICS = {
  totalMemberCount: 1250,
  totalSelfCount: 520,
  totalDependentCount: 730,
  totalEnrolledCount: 1195,
  totalFailedCount: 55,
};

export const MOCK_MEMBERS = [
  {
    stagingMemberEnrollmentId: "SM-001",
    uhid: "MD-TCS-000101",
    insuredMemberUniqueHealthIdentificationNumber: "MD-TCS-000101",
    corporateEmployeeCode: "EMP-10492",
    healthCardNumber: "9102445188901234",
    insuredMemberName: "Rahul Rajesh Sharma",
    name: "Rahul Rajesh Sharma",
    insuredMemberDateOfBirth: "1988-06-15",
    dateOfBirth: "1988-06-15",
    insuredMemberAge: 36,
    age: 36,
    insuredMemberGender: "MALE",
    gender: "MALE",
    insuredMemberRelationshipWithSubscriber: "SELF",
    relationship: "SELF",
    policySumInsured: 500000,
    recordStatus: "ACTIVE",
    enrollmentStatus: "ENROLLED",
    exceptionCategory: "NONE",
    insuredMemberEmailId: "rahul.sharma@tcs.com",
    insuredMemberMobileNumber: "9820011223",
    corporateEmployeeDateOfJoining: "2018-07-01",
    policyRecordType: "CORPORATE",
    inwardNo: "INW-2024-00101",
    policyId: "POL001",
    corporateId: "CORP001",
  },
  {
    stagingMemberEnrollmentId: "SM-002",
    uhid: "MD-TCS-000102",
    insuredMemberUniqueHealthIdentificationNumber: "MD-TCS-000102",
    corporateEmployeeCode: "EMP-10492",
    healthCardNumber: "9102445188901235",
    insuredMemberName: "Sneha Rahul Sharma",
    name: "Sneha Rahul Sharma",
    insuredMemberDateOfBirth: "1990-09-24",
    dateOfBirth: "1990-09-24",
    insuredMemberAge: 34,
    age: 34,
    insuredMemberGender: "FEMALE",
    gender: "FEMALE",
    insuredMemberRelationshipWithSubscriber: "SPOUSE",
    relationship: "SPOUSE",
    policySumInsured: 500000,
    recordStatus: "ACTIVE",
    enrollmentStatus: "ENROLLED",
    exceptionCategory: "NONE",
    insuredMemberEmailId: "sneha.sharma@gmail.com",
    insuredMemberMobileNumber: "9820011224",
    corporateEmployeeDateOfJoining: "2018-07-01",
    policyRecordType: "CORPORATE",
    inwardNo: "INW-2024-00101",
    policyId: "POL001",
    corporateId: "CORP001",
  },
  {
    stagingMemberEnrollmentId: "SM-003",
    uhid: "MD-TCS-000103",
    insuredMemberUniqueHealthIdentificationNumber: "MD-TCS-000103",
    corporateEmployeeCode: "EMP-10492",
    healthCardNumber: "9102445188901236",
    insuredMemberName: "Aarav Rahul Sharma",
    name: "Aarav Rahul Sharma",
    insuredMemberDateOfBirth: "2016-03-12",
    dateOfBirth: "2016-03-12",
    insuredMemberAge: 8,
    age: 8,
    insuredMemberGender: "MALE",
    gender: "MALE",
    insuredMemberRelationshipWithSubscriber: "CHILD",
    relationship: "CHILD",
    policySumInsured: 500000,
    recordStatus: "ACTIVE",
    enrollmentStatus: "ENROLLED",
    exceptionCategory: "NONE",
    insuredMemberEmailId: "rahul.sharma@tcs.com",
    insuredMemberMobileNumber: "9820011223",
    corporateEmployeeDateOfJoining: "2018-07-01",
    policyRecordType: "CORPORATE",
    inwardNo: "INW-2024-00101",
    policyId: "POL001",
    corporateId: "CORP001",
  },
  {
    stagingMemberEnrollmentId: "SM-004",
    uhid: "MD-TCS-000201",
    insuredMemberUniqueHealthIdentificationNumber: "MD-TCS-000201",
    corporateEmployeeCode: "EMP-10501",
    healthCardNumber: "9102445188902201",
    insuredMemberName: "Vikram Nayan Patel",
    name: "Vikram Nayan Patel",
    insuredMemberDateOfBirth: "1982-11-10",
    dateOfBirth: "1982-11-10",
    insuredMemberAge: 42,
    age: 42,
    insuredMemberGender: "MALE",
    gender: "MALE",
    insuredMemberRelationshipWithSubscriber: "SELF",
    relationship: "SELF",
    policySumInsured: 500000,
    recordStatus: "ACTIVE",
    enrollmentStatus: "ENROLLED",
    exceptionCategory: "NONE",
    insuredMemberEmailId: "vikram.patel@tcs.com",
    insuredMemberMobileNumber: "9870022334",
    corporateEmployeeDateOfJoining: "2015-02-15",
    policyRecordType: "CORPORATE",
    inwardNo: "INW-2024-00101",
    policyId: "POL001",
    corporateId: "CORP001",
  },
  {
    stagingMemberEnrollmentId: "SM-005",
    uhid: "MD-TCS-000202",
    insuredMemberUniqueHealthIdentificationNumber: "MD-TCS-000202",
    corporateEmployeeCode: "EMP-10501",
    healthCardNumber: "9102445188902202",
    insuredMemberName: "Meera Vikram Patel",
    name: "Meera Vikram Patel",
    insuredMemberDateOfBirth: "1984-04-18",
    dateOfBirth: "1984-04-18",
    insuredMemberAge: 40,
    age: 40,
    insuredMemberGender: "FEMALE",
    gender: "FEMALE",
    insuredMemberRelationshipWithSubscriber: "SPOUSE",
    relationship: "SPOUSE",
    policySumInsured: 500000,
    recordStatus: "ACTIVE",
    enrollmentStatus: "ENROLLED",
    exceptionCategory: "NONE",
    insuredMemberEmailId: "meera.patel@gmail.com",
    insuredMemberMobileNumber: "9870022335",
    corporateEmployeeDateOfJoining: "2015-02-15",
    policyRecordType: "CORPORATE",
    inwardNo: "INW-2024-00101",
    policyId: "POL001",
    corporateId: "CORP001",
  },
  {
    stagingMemberEnrollmentId: "SM-006",
    uhid: "MD-TCS-000301",
    insuredMemberUniqueHealthIdentificationNumber: "MD-TCS-000301",
    corporateEmployeeCode: "EMP-10610",
    healthCardNumber: "9102445188903301",
    insuredMemberName: "Amit Suresh Joshi",
    name: "Amit Suresh Joshi",
    insuredMemberDateOfBirth: "1995-08-22",
    dateOfBirth: "1995-08-22",
    insuredMemberAge: 29,
    age: 29,
    insuredMemberGender: "MALE",
    gender: "MALE",
    insuredMemberRelationshipWithSubscriber: "SELF",
    relationship: "SELF",
    policySumInsured: 500000,
    recordStatus: "ACTIVE",
    enrollmentStatus: "ENROLLED",
    exceptionCategory: "NONE",
    insuredMemberEmailId: "amit.joshi@tcs.com",
    insuredMemberMobileNumber: "9833044556",
    corporateEmployeeDateOfJoining: "2021-09-01",
    policyRecordType: "CORPORATE",
    inwardNo: "INW-2024-00101",
    policyId: "POL001",
    corporateId: "CORP001",
  },
  {
    stagingMemberEnrollmentId: "SM-007",
    uhid: "MD-TCS-000401",
    insuredMemberUniqueHealthIdentificationNumber: "MD-TCS-000401",
    corporateEmployeeCode: "EMP-10755",
    healthCardNumber: "9102445188904401",
    insuredMemberName: "Pooja Raman Nair",
    name: "Pooja Raman Nair",
    insuredMemberDateOfBirth: "1991-01-30",
    dateOfBirth: "1991-01-30",
    insuredMemberAge: 33,
    age: 33,
    insuredMemberGender: "FEMALE",
    gender: "FEMALE",
    insuredMemberRelationshipWithSubscriber: "SELF",
    relationship: "SELF",
    policySumInsured: 500000,
    recordStatus: "ACTIVE",
    enrollmentStatus: "ENROLLED",
    exceptionCategory: "NONE",
    insuredMemberEmailId: "pooja.nair@tcs.com",
    insuredMemberMobileNumber: "9811055667",
    corporateEmployeeDateOfJoining: "2019-11-15",
    policyRecordType: "CORPORATE",
    inwardNo: "INW-2024-00101",
    policyId: "POL001",
    corporateId: "CORP001",
  },
  {
    stagingMemberEnrollmentId: "SM-008",
    uhid: "MD-TCS-000402",
    insuredMemberUniqueHealthIdentificationNumber: "MD-TCS-000402",
    corporateEmployeeCode: "EMP-10755",
    healthCardNumber: "9102445188904402",
    insuredMemberName: "Ananya Nair",
    name: "Ananya Nair",
    insuredMemberDateOfBirth: "2020-05-14",
    dateOfBirth: "2020-05-14",
    insuredMemberAge: 4,
    age: 4,
    insuredMemberGender: "FEMALE",
    gender: "FEMALE",
    insuredMemberRelationshipWithSubscriber: "CHILD",
    relationship: "CHILD",
    policySumInsured: 500000,
    recordStatus: "ACTIVE",
    enrollmentStatus: "ENROLLED",
    exceptionCategory: "NONE",
    insuredMemberEmailId: "pooja.nair@tcs.com",
    insuredMemberMobileNumber: "9811055667",
    corporateEmployeeDateOfJoining: "2019-11-15",
    policyRecordType: "CORPORATE",
    inwardNo: "INW-2024-00101",
    policyId: "POL001",
    corporateId: "CORP001",
  },
  {
    stagingMemberEnrollmentId: "SM-009",
    uhid: "MD-TCS-000501",
    insuredMemberUniqueHealthIdentificationNumber: "MD-TCS-000501",
    corporateEmployeeCode: "EMP-10820",
    healthCardNumber: "9102445188905501",
    insuredMemberName: "Sandeep Vinayak Kulkarni",
    name: "Sandeep Vinayak Kulkarni",
    insuredMemberDateOfBirth: "1974-12-05",
    dateOfBirth: "1974-12-05",
    insuredMemberAge: 50,
    age: 50,
    insuredMemberGender: "MALE",
    gender: "MALE",
    insuredMemberRelationshipWithSubscriber: "SELF",
    relationship: "SELF",
    policySumInsured: 500000,
    recordStatus: "ACTIVE",
    enrollmentStatus: "ENROLLED",
    exceptionCategory: "NONE",
    insuredMemberEmailId: "sandeep.kulkarni@tcs.com",
    insuredMemberMobileNumber: "9822066778",
    corporateEmployeeDateOfJoining: "2012-04-10",
    policyRecordType: "CORPORATE",
    inwardNo: "INW-2024-00101",
    policyId: "POL001",
    corporateId: "CORP001",
  },
  {
    stagingMemberEnrollmentId: "SM-010",
    uhid: "MD-TCS-000502",
    insuredMemberUniqueHealthIdentificationNumber: "MD-TCS-000502",
    corporateEmployeeCode: "EMP-10820",
    healthCardNumber: "9102445188905502",
    insuredMemberName: "Shobha Sandeep Kulkarni",
    name: "Shobha Sandeep Kulkarni",
    insuredMemberDateOfBirth: "1977-03-19",
    dateOfBirth: "1977-03-19",
    insuredMemberAge: 47,
    age: 47,
    insuredMemberGender: "FEMALE",
    gender: "FEMALE",
    insuredMemberRelationshipWithSubscriber: "SPOUSE",
    relationship: "SPOUSE",
    policySumInsured: 500000,
    recordStatus: "ACTIVE",
    enrollmentStatus: "ENROLLED",
    exceptionCategory: "NONE",
    insuredMemberEmailId: "shobha.kulkarni@gmail.com",
    insuredMemberMobileNumber: "9822066779",
    corporateEmployeeDateOfJoining: "2012-04-10",
    policyRecordType: "CORPORATE",
    inwardNo: "INW-2024-00101",
    policyId: "POL001",
    corporateId: "CORP001",
  },
];

export const MOCK_FAILED_MEMBERS = [
  {
    stagingMemberEnrollmentId: "SM-FAIL-001",
    uhid: "MD-TCS-009901",
    insuredMemberUniqueHealthIdentificationNumber: "MD-TCS-009901",
    corporateEmployeeCode: "EMP-10511",
    healthCardNumber: "",
    insuredMemberName: "Priya Aniket Deshmukh",
    name: "Priya Aniket Deshmukh",
    insuredMemberDateOfBirth: "1994-11-20",
    dateOfBirth: "1994-11-20",
    insuredMemberAge: 30,
    age: 30,
    insuredMemberGender: "FEMALE",
    gender: "FEMALE",
    insuredMemberRelationshipWithSubscriber: "SPOUSE",
    relationship: "SPOUSE",
    policySumInsured: 500000,
    recordStatus: "FAILED",
    enrollmentStatus: "VALIDATION_FAILED",
    enrollmentStatusReason: "[ERR_INVALID_DOB] Member date of birth in roster does not match with government identity verification",
    insuredMemberEmailId: "priya.deshmukh@gmail.com",
    insuredMemberMobileNumber: "9820099881",
    corporateEmployeeDateOfJoining: "2020-03-01",
    policyRecordType: "CORPORATE",
    inwardNo: "INW-2024-00101",
    policyId: "POL001",
    corporateId: "CORP001",
  },
  {
    stagingMemberEnrollmentId: "SM-FAIL-002",
    uhid: "MD-TCS-009902",
    insuredMemberUniqueHealthIdentificationNumber: "MD-TCS-009902",
    corporateEmployeeCode: "EMP-10580",
    healthCardNumber: "",
    insuredMemberName: "Rohan Alok Kapoor",
    name: "Rohan Alok Kapoor",
    insuredMemberDateOfBirth: "1998-05-14",
    dateOfBirth: "1998-05-14",
    insuredMemberAge: 26,
    age: 26,
    insuredMemberGender: "MALE",
    gender: "MALE",
    insuredMemberRelationshipWithSubscriber: "CHILD",
    relationship: "CHILD",
    policySumInsured: 500000,
    recordStatus: "FAILED",
    enrollmentStatus: "VALIDATION_FAILED",
    enrollmentStatusReason: "[ERR_OVERAGE] Dependent child age exceeds maximum policy eligibility limit of 25 years",
    insuredMemberEmailId: "rohan.kapoor@gmail.com",
    insuredMemberMobileNumber: "9820099882",
    corporateEmployeeDateOfJoining: "2017-08-15",
    policyRecordType: "CORPORATE",
    inwardNo: "INW-2024-00101",
    policyId: "POL001",
    corporateId: "CORP001",
  },
  {
    stagingMemberEnrollmentId: "SM-FAIL-003",
    uhid: "MD-TCS-009903",
    insuredMemberUniqueHealthIdentificationNumber: "MD-TCS-009903",
    corporateEmployeeCode: "EMP-10642",
    healthCardNumber: "",
    insuredMemberName: "Rajeshwar Dayal Verma",
    name: "Rajeshwar Dayal Verma",
    insuredMemberDateOfBirth: "1942-02-18",
    dateOfBirth: "1942-02-18",
    insuredMemberAge: 82,
    age: 82,
    insuredMemberGender: "MALE",
    gender: "MALE",
    insuredMemberRelationshipWithSubscriber: "PARENT",
    relationship: "PARENT",
    policySumInsured: 500000,
    recordStatus: "FAILED",
    enrollmentStatus: "VALIDATION_FAILED",
    enrollmentStatusReason: "[ERR_PARENT_AGE] Senior parent age exceeds 80-year entry ceiling without underwriter exemption",
    insuredMemberEmailId: "rd.verma@gmail.com",
    insuredMemberMobileNumber: "9820099883",
    corporateEmployeeDateOfJoining: "2016-01-10",
    policyRecordType: "CORPORATE",
    inwardNo: "INW-2024-00101",
    policyId: "POL001",
    corporateId: "CORP001",
  },
];

export const MOCK_EXCEPTION_SUMMARY = [
  { category: "OVER_AGE_DEPENDENT", memberCount: 12 },
  { category: "SUM_INSURED_EXCEEDED", memberCount: 8 },
  { category: "NAME_MISMATCH_WITH_AADHAAR", memberCount: 15 },
  { category: "DUPLICATE_FAMILY_MEMBER", memberCount: 5 },
  { category: "MISSING_EMPLOYEE_JOINING_DATE", memberCount: 9 },
];

export const MOCK_EXCEPTION_MEMBERS = [
  {
    stagingMemberEnrollmentId: "SM-EXC-001",
    corporateEmployeeCode: "EMP-10580",
    insuredMemberName: "Rohan Alok Kapoor",
    insuredMemberDateOfBirth: "1998-05-14",
    insuredMemberAge: 26,
    insuredMemberGender: "MALE",
    insuredMemberRelationshipWithSubscriber: "CHILD",
    insuredMemberUniqueHealthIdentificationNumber: "MD-TCS-EXC-001",
    insuredMemberEmailId: "rohan.kapoor@gmail.com",
    corporateEmployeeDateOfJoining: "2017-08-15",
    exceptionCategory: "OVER_AGE_DEPENDENT",
    status: "EXCEPTION_PENDING",
  },
  {
    stagingMemberEnrollmentId: "SM-EXC-002",
    corporateEmployeeCode: "EMP-10585",
    insuredMemberName: "Kavita Mahesh Bhatt",
    insuredMemberDateOfBirth: "1997-09-08",
    insuredMemberAge: 27,
    insuredMemberGender: "FEMALE",
    insuredMemberRelationshipWithSubscriber: "CHILD",
    insuredMemberUniqueHealthIdentificationNumber: "MD-TCS-EXC-002",
    insuredMemberEmailId: "kavita.bhatt@gmail.com",
    corporateEmployeeDateOfJoining: "2019-04-12",
    exceptionCategory: "OVER_AGE_DEPENDENT",
    status: "EXCEPTION_PENDING",
  },
  {
    stagingMemberEnrollmentId: "SM-EXC-003",
    corporateEmployeeCode: "EMP-10642",
    insuredMemberName: "Rajeshwar Dayal Verma",
    insuredMemberDateOfBirth: "1942-02-18",
    insuredMemberAge: 82,
    insuredMemberGender: "MALE",
    insuredMemberRelationshipWithSubscriber: "PARENT",
    insuredMemberUniqueHealthIdentificationNumber: "MD-TCS-EXC-003",
    insuredMemberEmailId: "rd.verma@gmail.com",
    corporateEmployeeDateOfJoining: "2016-01-10",
    exceptionCategory: "OVER_AGE_DEPENDENT",
    status: "EXCEPTION_PENDING",
  },
  {
    stagingMemberEnrollmentId: "SM-EXC-004",
    corporateEmployeeCode: "EMP-10701",
    insuredMemberName: "Devendra Pratap Singh",
    insuredMemberDateOfBirth: "1975-07-21",
    insuredMemberAge: 49,
    insuredMemberGender: "MALE",
    insuredMemberRelationshipWithSubscriber: "SELF",
    insuredMemberUniqueHealthIdentificationNumber: "MD-TCS-EXC-004",
    insuredMemberEmailId: "devendra.singh@tcs.com",
    corporateEmployeeDateOfJoining: "2014-06-01",
    exceptionCategory: "SUM_INSURED_EXCEEDED",
    status: "EXCEPTION_PENDING",
  },
  {
    stagingMemberEnrollmentId: "SM-EXC-005",
    corporateEmployeeCode: "EMP-10788",
    insuredMemberName: "Anjali Gupta",
    insuredMemberDateOfBirth: "1992-12-05",
    insuredMemberAge: 32,
    insuredMemberGender: "FEMALE",
    insuredMemberRelationshipWithSubscriber: "SELF",
    insuredMemberUniqueHealthIdentificationNumber: "MD-TCS-EXC-005",
    insuredMemberEmailId: "anjali.gupta@tcs.com",
    corporateEmployeeDateOfJoining: "2020-10-15",
    exceptionCategory: "NAME_MISMATCH_WITH_AADHAAR",
    status: "EXCEPTION_PENDING",
  },
];

export const MOCK_DISCREPANCY_MEMBERS = [
  {
    stagingMemberEnrollmentId: "SM-DISC-001",
    insuredMemberName: "Anjali Gupta",
    corporateEmployeeCode: "EMP-10788",
    uhid: "MD-TCS-DISC-01",
    discrepancyType: "NAME_SPELLING_MISMATCH",
    fieldDiscrepancyRemark: "Roster Name: 'Anjali Gupta', Aadhaar Verified Name: 'Gupta Anjali Kumari'",
    policySumInsured: 500000,
    status: "DISCREPANCY_FLAGGED",
  },
  {
    stagingMemberEnrollmentId: "SM-DISC-002",
    insuredMemberName: "Manoj Kumar Yadav",
    corporateEmployeeCode: "EMP-10815",
    uhid: "MD-TCS-DISC-02",
    discrepancyType: "GENDER_MISMATCH",
    fieldDiscrepancyRemark: "Roster Gender: 'FEMALE', Government ID Gender: 'MALE'",
    policySumInsured: 500000,
    status: "DISCREPANCY_FLAGGED",
  },
];

export const MOCK_RECONCILIATION_REPORT = [
  {
    uhid: "MD-TCS-000101",
    name: "Rahul Rajesh Sharma",
    corporateEmployeeCode: "EMP-10492",
    relationship: "SELF",
    gender: "MALE",
    dateOfBirth: "1988-06-15",
    age: 36,
    policyRecordType: "CORPORATE",
    reconciliationStatus: "EXISTING_MEMBER_MATCHED",
    reconciliationRemark: "Member successfully verified and matched with previous policy period records.",
  },
  {
    uhid: "MD-TCS-000102",
    name: "Sneha Rahul Sharma",
    corporateEmployeeCode: "EMP-10492",
    relationship: "SPOUSE",
    gender: "FEMALE",
    dateOfBirth: "1990-09-24",
    age: 34,
    policyRecordType: "CORPORATE",
    reconciliationStatus: "NEW_ENROLLED",
    reconciliationRemark: "Newly enrolled dependent spouse under family floater policy cover.",
  },
  {
    uhid: "MD-TCS-000205",
    name: "Karan Mehta",
    corporateEmployeeCode: "EMP-08912",
    relationship: "SELF",
    gender: "MALE",
    dateOfBirth: "1985-03-12",
    age: 39,
    policyRecordType: "CORPORATE",
    reconciliationStatus: "MEMBER_DELETED",
    reconciliationRemark: "Employee separated from company; deleted from active member roster.",
  },
  {
    uhid: "MD-TCS-000318",
    name: "Anjali Gupta",
    corporateEmployeeCode: "EMP-11200",
    relationship: "SELF",
    gender: "FEMALE",
    dateOfBirth: "1992-12-05",
    age: 32,
    policyRecordType: "CORPORATE",
    reconciliationStatus: "PARTIAL_MISMATCH",
    reconciliationRemark: "Name order discrepancy: Aadhaar shows 'Gupta Anjali', Excel roster shows 'Anjali Gupta'.",
  },
];

export const MOCK_ECARD_TEMPLATES = [
  {
    id: "TPL001",
    templateId: "TPL001",
    templateName: "MD India Standard Corporate E-Card",
    insurerName: "National Insurance Company Limited",
    insurerId: "INS001",
    policyType: "CORPORATE_GMC",
    cardOrientation: "HORIZONTAL",
    status: "ACTIVE",
    version: "2.0",
    effectiveFrom: "2024-01-01",
  },
  {
    id: "TPL002",
    templateId: "TPL002",
    templateName: "Executive Golden Floater E-Card",
    insurerName: "The New India Assurance Co. Ltd.",
    insurerId: "INS002",
    policyType: "CORPORATE_GMC",
    cardOrientation: "HORIZONTAL",
    status: "ACTIVE",
    version: "1.5",
    effectiveFrom: "2024-01-01",
  },
  {
    id: "TPL003",
    templateId: "TPL003",
    templateName: "Star Health Comprehensive E-Card",
    insurerName: "Star Health and Allied Insurance Co. Ltd.",
    insurerId: "INS005",
    policyType: "RETAIL_HEALTH",
    cardOrientation: "HORIZONTAL",
    status: "ACTIVE",
    version: "1.0",
    effectiveFrom: "2024-03-01",
  },
];

export const MOCK_USERS = [
  {
    userId: "USR-001",
    id: "USR-001",
    username: "processor_tpa",
    name: "Pooja Deshmukh",
    email: "pooja.d@mdindia.com",
    role: "corporate_enrolment_processor",
    department: "Enrollment Operations",
    status: "ACTIVE",
  },
  {
    userId: "USR-002",
    id: "USR-002",
    username: "qc_lead",
    name: "Vikram Jadhav",
    email: "vikram.j@mdindia.com",
    role: "corporate_enrolment_qc",
    department: "Quality Control",
    status: "ACTIVE",
  },
  {
    userId: "USR-003",
    id: "USR-003",
    username: "admin_ops",
    name: "Sunil Kothari",
    email: "sunil.k@mdindia.com",
    role: "corporate_enrolment_admin",
    department: "Operations Management",
    status: "ACTIVE",
  },
];
