// src/services/mockProviderData.ts

export const MOCK_DEPARTMENTS = [
  {
    departmentId: "DEP-PROV-001",
    departmentName: "Provider Network",
    tpaDepartmentActiveFlag: true,
    description: "Provider Hospital Empanelment, Network Contracting & Tariff Management",
  },
  {
    departmentId: "DEP-ENR-002",
    departmentName: "Enrollment",
    tpaDepartmentActiveFlag: true,
    description: "Corporate & Retail Policy Enrollment Operations",
  },
  {
    departmentId: "DEP-CLM-003",
    departmentName: "Claims Operations",
    tpaDepartmentActiveFlag: true,
    description: "Cashless Authorization & Reimbursement Processing",
  },
  {
    departmentId: "DEP-FIN-004",
    departmentName: "Finance & Accounts",
    tpaDepartmentActiveFlag: true,
    description: "Hospital Settlement, Billing & Reconciliation",
  },
];

/**
 * Generate ISO timestamps ensuring "Today's Inward" is always populated
 * on the current local calendar day regardless of what time of day it is.
 */
function getTodayIso(hour: number = 10, minute: number = 0): string {
  const d = new Date();
  d.setHours(hour, minute, 0, 0);
  return d.toISOString();
}

function getPastDateIso(daysAgo: number, hour: number = 10): string {
  const d = new Date();
  d.setDate(d.getDate() - daysAgo);
  d.setHours(hour, 0, 0, 0);
  return d.toISOString();
}

export const MOCK_PROVIDER_INWARDS = [
  // --- TODAY'S INWARDS (4 records: 1 Pending, 1 Processing/QC, 1 Completed, 1 Rejected) ---
  {
    id: "INW-PRV-101",
    inwardNo: "INW-2024-PRV-001",
    inwardReceivedAt: getTodayIso(9, 30),
    createdAt: getTodayIso(9, 30),
    sourceEntityName: "Apollo Hospital International",
    inwardSourceEntityId: "HOSP001",
    inwardSourceEntityType: "HOSPITAL",
    departmentId: "DEP-PROV-001",
    departmentName: "Provider Network",
    s3SubBucketName: "IC_PROVIDER_MAPPING",
    documentType: "IC_PROVIDER_MAPPING",
    status: "PROCESSOR_PENDING",
    recordStatus: "ACTIVE",
    assignedTo: "Rahul Kumar",
    createdBy: "pooja.deshmukh",
    originalFileName: "Apollo_IC_Mapping_Request_2024.xlsx",
    isToday: true,
  },
  {
    id: "INW-PRV-102",
    inwardNo: "INW-2024-PRV-002",
    inwardReceivedAt: getTodayIso(10, 45),
    createdAt: getTodayIso(10, 45),
    sourceEntityName: "Fortis Memorial Research Institute",
    inwardSourceEntityId: "HOSP002",
    inwardSourceEntityType: "HOSPITAL",
    departmentId: "DEP-PROV-001",
    departmentName: "Provider Network",
    s3SubBucketName: "EMPANELMENT",
    documentType: "HOSPITAL_EMPANELMENT_REQUEST",
    status: "QC_PENDING",
    recordStatus: "ACTIVE",
    assignedTo: "Anup Kalam",
    createdBy: "vikram.jadhav",
    originalFileName: "Fortis_Empanelment_Application_Signed.pdf",
    isToday: true,
  },
  {
    id: "INW-PRV-103",
    inwardNo: "INW-2024-PRV-003",
    inwardReceivedAt: getTodayIso(11, 20),
    createdAt: getTodayIso(11, 20),
    sourceEntityName: "Manipal Hospital Old Airport Road",
    inwardSourceEntityId: "HOSP003",
    inwardSourceEntityType: "HOSPITAL",
    departmentId: "DEP-PROV-001",
    departmentName: "Provider Network",
    s3SubBucketName: "SOC_DISCOUNT",
    documentType: "TARIFF_REVISION",
    status: "COMPLETED",
    recordStatus: "ACTIVE",
    assignedTo: "Tushar Kale",
    createdBy: "admin.user",
    originalFileName: "Manipal_2024_Revised_SOC_Schedule.pdf",
    isToday: true,
  },
  {
    id: "INW-PRV-104",
    inwardNo: "INW-2024-PRV-004",
    inwardReceivedAt: getTodayIso(14, 15),
    createdAt: getTodayIso(14, 15),
    sourceEntityName: "Ruby Hall Clinic Sassoon Road",
    inwardSourceEntityId: "HOSP004",
    inwardSourceEntityType: "HOSPITAL",
    departmentId: "DEP-PROV-001",
    departmentName: "Provider Network",
    s3SubBucketName: "BANK_VERIFICATION",
    documentType: "BANK_MANDATE",
    status: "REJECTED_INWARD",
    recordStatus: "ACTIVE",
    assignedTo: "Megha Patil",
    createdBy: "pooja.deshmukh",
    originalFileName: "RubyHall_Cancelled_Cheque_BankMandate.pdf",
    isToday: true,
  },

  // --- PAST INWARDS (4 records: 1 Pending, 1 Processing/QC, 2 Completed) ---
  {
    id: "INW-PRV-105",
    inwardNo: "INW-2024-PRV-005",
    inwardReceivedAt: getPastDateIso(3, 10),
    createdAt: getPastDateIso(3, 10),
    sourceEntityName: "Max Super Speciality Hospital Saket",
    inwardSourceEntityId: "HOSP005",
    inwardSourceEntityType: "HOSPITAL",
    departmentId: "DEP-PROV-001",
    departmentName: "Provider Network",
    s3SubBucketName: "IC_PROVIDER_MAPPING",
    documentType: "IC_PROVIDER_MAPPING",
    status: "COMPLETED",
    recordStatus: "ACTIVE",
    assignedTo: "Vikram Shah",
    createdBy: "admin.user",
    originalFileName: "Max_Saket_MOU_Extension_Signed.pdf",
    isToday: false,
  },
  {
    id: "INW-PRV-106",
    inwardNo: "INW-2024-PRV-006",
    inwardReceivedAt: getPastDateIso(4, 11),
    createdAt: getPastDateIso(4, 11),
    sourceEntityName: "Kokilaben Dhirubhai Ambani Hospital",
    inwardSourceEntityId: "HOSP006",
    inwardSourceEntityType: "HOSPITAL",
    departmentId: "DEP-PROV-001",
    departmentName: "Provider Network",
    s3SubBucketName: "EXCLUSION_REQUEST",
    documentType: "EXCLUSION_REQUEST",
    status: "PROCESSOR_PENDING",
    recordStatus: "ACTIVE",
    assignedTo: "Rahul Kumar",
    createdBy: "pooja.deshmukh",
    originalFileName: "KDAH_Temporary_Delist_Notice.pdf",
    isToday: false,
  },
  {
    id: "INW-PRV-107",
    inwardNo: "INW-2024-PRV-007",
    inwardReceivedAt: getPastDateIso(6, 14),
    createdAt: getPastDateIso(6, 14),
    sourceEntityName: "Care Hospital Banjara Hills",
    inwardSourceEntityId: "HOSP007",
    inwardSourceEntityType: "HOSPITAL",
    departmentId: "DEP-PROV-001",
    departmentName: "Provider Network",
    s3SubBucketName: "EMPANELMENT",
    documentType: "HOSPITAL_EMPANELMENT_REQUEST",
    status: "QC_PENDING",
    recordStatus: "ACTIVE",
    assignedTo: "Anup Kalam",
    createdBy: "vikram.jadhav",
    originalFileName: "Care_Hospitals_Empanelment_Dossier.pdf",
    isToday: false,
  },
  {
    id: "INW-PRV-108",
    inwardNo: "INW-2024-PRV-008",
    inwardReceivedAt: getPastDateIso(9, 16),
    createdAt: getPastDateIso(9, 16),
    sourceEntityName: "Deenanath Mangeshkar Hospital",
    inwardSourceEntityId: "HOSP008",
    inwardSourceEntityType: "HOSPITAL",
    departmentId: "DEP-PROV-001",
    departmentName: "Provider Network",
    s3SubBucketName: "SOC_DISCOUNT",
    documentType: "TARIFF_REVISION",
    status: "COMPLETED",
    recordStatus: "ACTIVE",
    assignedTo: "Tushar Kale",
    createdBy: "admin.user",
    originalFileName: "Deenanath_Discount_Structure_2024.pdf",
    isToday: false,
  },
];

export const MOCK_ROHINI_LIST = [
  {
    id: "ROH-001",
    rohiniId: "ROH-001",
    iibRohiniCode: "ROH-APO-88912",
    hospitalName: "Apollo Hospital International",
    address: "Plot 1A, GIDC Estate, Gandhinagar Highway",
    city: "Ahmedabad",
    state: "Gujarat",
    pincode: "382428",
    totalBeds: 350,
    status: "ACTIVE",
    hospitalType: "CORPORATE_HOSPITAL",
    systemOfMedicine: "ALLOPATHY",
    pan: "AAACA1234E",
    effectiveFrom: "2020-01-01",
    effectiveTo: "2027-12-31",
  },
  {
    id: "ROH-002",
    rohiniId: "ROH-002",
    iibRohiniCode: "ROH-FOR-77123",
    hospitalName: "Fortis Memorial Research Institute",
    address: "Sector 44, Opposite HUDA City Centre",
    city: "Gurugram",
    state: "Haryana",
    pincode: "122002",
    totalBeds: 400,
    status: "ACTIVE",
    hospitalType: "CORPORATE_HOSPITAL",
    systemOfMedicine: "ALLOPATHY",
    pan: "AAACF5678G",
    effectiveFrom: "2021-04-15",
    effectiveTo: "2026-04-14",
  },
  {
    id: "ROH-003",
    rohiniId: "ROH-003",
    iibRohiniCode: "ROH-MAN-99001",
    hospitalName: "Manipal Hospital Old Airport Road",
    address: "98, HAL Old Airport Rd, Kodihalli",
    city: "Bengaluru",
    state: "Karnataka",
    pincode: "560017",
    totalBeds: 600,
    status: "ACTIVE",
    hospitalType: "CORPORATE_HOSPITAL",
    systemOfMedicine: "ALLOPATHY",
    pan: "AAACM9012K",
    effectiveFrom: "2019-01-01",
    effectiveTo: "2026-12-31",
  },
  {
    id: "ROH-004",
    rohiniId: "ROH-004",
    iibRohiniCode: "ROH-RUB-44321",
    hospitalName: "Ruby Hall Clinic Sassoon Road",
    address: "40, Sassoon Road, Sangamvadi",
    city: "Pune",
    state: "Maharashtra",
    pincode: "411001",
    totalBeds: 550,
    status: "ACTIVE",
    hospitalType: "TRUST_HOSPITAL",
    systemOfMedicine: "ALLOPATHY",
    pan: "AAACR3456L",
    effectiveFrom: "2018-03-01",
    effectiveTo: "2027-02-28",
  },
  {
    id: "ROH-005",
    rohiniId: "ROH-005",
    iibRohiniCode: "ROH-MAX-55678",
    hospitalName: "Max Super Speciality Hospital Saket",
    address: "1, 2, Press Enclave Marg, Saket",
    city: "New Delhi",
    state: "Delhi",
    pincode: "110017",
    totalBeds: 500,
    status: "ACTIVE",
    hospitalType: "CORPORATE_HOSPITAL",
    systemOfMedicine: "ALLOPATHY",
    pan: "AAACM7890P",
    effectiveFrom: "2020-06-01",
    effectiveTo: "2027-05-31",
  },
];

export const MOCK_PROVIDER_SYSTEM_OF_MEDICINE = [
  { id: "MED-001", name: "Allopathy", code: "ALLO", status: "ACTIVE" },
  { id: "MED-002", name: "Ayurveda", code: "AYUR", status: "ACTIVE" },
  { id: "MED-003", name: "Homeopathy", code: "HOME", status: "ACTIVE" },
  { id: "MED-004", name: "Unani", code: "UNAN", status: "ACTIVE" },
  { id: "MED-005", name: "Siddha", code: "SIDD", status: "ACTIVE" },
];

export const MOCK_PROVIDER_IDENTIFIER_TYPES = [
  { id: "IDT-001", identifierCode: "PAN", identifierName: "Permanent Account Number", regex: "^[A-Z]{5}[0-9]{4}[A-Z]{1}$", status: "ACTIVE" },
  { id: "IDT-002", identifierCode: "ROHINI", identifierName: "ROHINI Code", regex: "^[A-Z0-9-]{6,20}$", status: "ACTIVE" },
  { id: "IDT-003", identifierCode: "NABH", identifierName: "NABH Accreditation Number", regex: "^[A-Z0-9-]{4,25}$", status: "ACTIVE" },
  { id: "IDT-004", identifierCode: "CLE", identifierName: "Clinical Establishment License", regex: "^[A-Z0-9-]{4,30}$", status: "ACTIVE" },
  { id: "IDT-005", identifierCode: "GSTIN", identifierName: "GST Identification Number", regex: "^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$", status: "ACTIVE" },
];

export const MOCK_PROVIDER_TAXONOMY = [
  { id: "TAX-001", taxonomyCode: "MULTI_SPECIALITY", taxonomyName: "Multi-Speciality Hospital", description: "Facilities offering 3 or more surgical and medical specialties", status: "ACTIVE" },
  { id: "TAX-002", taxonomyCode: "SUPER_SPECIALITY", taxonomyName: "Super-Speciality Tertiary Care", description: "Advanced tertiary/quaternary care with specialized ICUs and organ transplant", status: "ACTIVE" },
  { id: "TAX-003", taxonomyCode: "SINGLE_SPECIALITY_EYE", taxonomyName: "Eye Care / Ophthalmology Center", description: "Specialized eye hospital and refractive surgery center", status: "ACTIVE" },
  { id: "TAX-004", taxonomyCode: "DIAGNOSTIC_IMAGING", taxonomyName: "Diagnostic & Advanced Imaging Center", description: "Standalone pathology and radio-diagnosis facility", status: "ACTIVE" },
  { id: "TAX-005", taxonomyCode: "DAY_CARE_SURGICAL", taxonomyName: "Day Care Surgical Center", description: "Short-stay surgical and endoscopy daycare unit", status: "ACTIVE" },
];

export const MOCK_NETWORK_MODES = [
  { id: "MOD-001", modeCode: "GIPSA_PPN", modeName: "GIPSA Preferred Provider Network (PPN)", status: "ACTIVE" },
  { id: "MOD-002", modeCode: "DIRECT_AGREEMENT", modeName: "Direct MD India TPA Bilateral Agreement", status: "ACTIVE" },
  { id: "MOD-003", modeCode: "INSURER_CUSTOM_PPN", modeName: "Insurer Custom Preferred Network", status: "ACTIVE" },
  { id: "MOD-004", modeCode: "NON_NETWORK", modeName: "Non-Network / Reimbursement Only", status: "ACTIVE" },
];

export const MOCK_DISCOUNT_TYPES = [
  { id: "DISC-001", discountTypeCode: "IPD_ALL", discountTypeName: "Comprehensive IPD Bill Discount", defaultPercentage: 12.5, status: "ACTIVE" },
  { id: "DISC-002", discountTypeCode: "OPD_CONSULT", discountTypeName: "OPD Consultation Discount", defaultPercentage: 15.0, status: "ACTIVE" },
  { id: "DISC-003", discountTypeCode: "DIAGNOSTICS", discountTypeName: "Investigation & Diagnostics Discount", defaultPercentage: 10.0, status: "ACTIVE" },
  { id: "DISC-004", discountTypeCode: "PHARMACY", discountTypeName: "In-House Pharmacy Discount", defaultPercentage: 8.0, status: "ACTIVE" },
];

export const MOCK_PROVIDER_DETAILS_MAP: Record<string, any> = {
  HOSP001: {
    providerId: "HOSP001",
    providerName: "Apollo Hospital International",
    providerType: "HOSPITAL",
    providerTypeId: "HOSP",
    providerTypeName: "Hospital",
    providerClass: "TERTIARY",
    providerSubclass: "SUPER_SPECIALITY",
    providerCode: "MDI-HOSP-001",
    providerIibRohiniCode: "ROH-APO-88912",
    providerOldCode: JSON.stringify([
      { code: "OLD-APO-991", active: true },
      { code: "LEG-APO-012", active: false },
    ]),
    recordStatus: "ACTIVE",
    providerIsVerified: true,
    providerOwnershipType: "Private",
    providerDayCareFlag: true,
    providerCareTier: "Tertiary",
    providerInternalGrade: "A",
    providerOwnerName: "Dr. Prathap C. Reddy",
    providerOwnerDesignation: "Executive Chairman",
    providerOwnerQualification: "MD, FRCS (Cardiology)",
    providerSignatoryName: "Dr. Suneeta Reddy",
    providerSignatoryDesignation: "Managing Director",
    providerSystemOfMedicineName: "Allopathy",
    providerSystemOfMedicineId: "MED-001",
    providerEmpanellmentId: "EMP-2024-001",
    providerTpaServicingBranchId: "BR001",
    providerTpaServicingBranchName: "Pune-HO",
    tpaServicingBranchName: "Pune-HO",
    tpaServicingBranchEmail: ["pune.branch@mdindia.com", "network.support@mdindia.com"],
    providerServiceEmailId: "apollo.servicing@mdindia.com",
    providerAddress: "Plot 1A, GIDC Estate, Gandhinagar Highway",
    providerAddressId: "ADDR-001",
    providerPlotNo: "Plot 1A",
    providerLocation: "Metro",
    providerTaluka: "Gandhinagar",
    providerStateCode: "GJ",
    providerStateName: "Gujarat",
    providerCountryCode: "IN",
    providerLatitude: 23.1234,
    providerLongitude: 72.6345,
    providerAddressStatus: "VERIFIED",
    providerCity: "Ahmedabad",
    providerDistrict: "Gandhinagar",
    providerZone: "West",
    providerPostalCode: "382428",
    providerLocationType: "Metro",
    providerNetworkType: "NETWORK",
    tpaProviderNetwork: "NETWORK",
    insurerProviderNetwork: "GIPSA_PPN",
    providerRegistrationNo: "REG-GJ-2018-9921",
    providerRegistrationAuthority: "Gujarat State Health Systems Resource Centre",
    providerPanNo: "AAACA1234F",
    providerPanHolderName: "Apollo Hospitals Enterprise Ltd",
    providerTanNo: "AHMA12345B",
    providerContactDetail: {
      providerWebsiteAvailableFlag: true,
      providerWebsiteUrl: "https://www.apollohospitals.com/ahmedabad",
      providerTelephoneNo: ["079-66701800"],
      providerFaxNo: ["079-66701805"],
      providerMobileNo: ["9876543210"],
      providerEmailId: ["info.ahmedabad@apollohospitals.com", "tpa.helpdesk@apollohospitals.com"],
    },
    identifiers: [
      {
        identifierType: "ROHINI_CODE",
        identifierTypeName: "ROHINI_CODE", isPrimary: true, identifierStatus: "ACTIVE", issuingAuthorityName: "Insurance Information Bureau of India",
        identifierValue: "ROH-APO-88912",
        validFrom: "2020-01-01",
        validTo: "2027-12-31",
        status: "ACTIVE",
      },
      {
        identifierType: "PAN",
        identifierTypeName: "PAN NO", identifierStatus: "ACTIVE", identifierHolderName: "Apollo Hospitals Enterprise Ltd",
        identifierValue: "AAACA1234F",
        validFrom: "2015-05-10",
        validTo: "2030-12-31",
        status: "ACTIVE",
      },
      {
        identifierType: "NABH",
        identifierTypeName: "NABH Accreditation",
        identifierValue: "NABH-2021-0891",
        validFrom: "2021-04-01",
        validTo: "2027-03-31",
        status: "ACTIVE",
      },
      {
        identifierType: "CLE",
        identifierTypeName: "Clinical Establishment License",
        identifierValue: "CLE-GJ-44910",
        validFrom: "2022-01-01",
        validTo: "2027-01-01",
        status: "ACTIVE",
      },
    ],
    certificates: [
      {
        certificateId: "CERT-001",
        type: "NABH",
        description: "Full NABH Hospital Accreditation Tier-1",
        status: "Registered",
        validFrom: "2021-04-01",
        validTo: "2027-03-31",
        registrationNo: "NABH-2021-0891",
        providerActName: "National Accreditation Board for Hospitals",
        providerActDescription: "Healthcare Quality & Patient Safety Compliance",
      },
      {
        certificateId: "CERT-002",
        type: "FIRE_SAFETY",
        description: "Fire NOC & Life Safety Clearance",
        status: "Registered",
        validFrom: "2023-01-01",
        validTo: "2026-12-31",
        registrationNo: "FS-GJ-2023-4412",
        providerActName: "National Building Code - Fire Safety Division",
        providerActDescription: "Fire Prevention and Protection Measures Standard",
      },
      {
        certificateId: "CERT-003",
        type: "POLLUTION_CONTROL",
        description: "Bio-Medical Waste Management Authorization",
        status: "Registered",
        validFrom: "2022-06-01",
        validTo: "2027-05-31",
        registrationNo: "PCB-BMW-8819",
        providerActName: "Gujarat Pollution Control Board",
        providerActDescription: "Bio-Medical Waste Management Rules 2016",
      },
    ],
    clinicalSpecialties: [
      "Cardiology & Cardio-Thoracic Surgery",
      "Neurology & Neuro Surgery",
      "Oncology & Medical Oncology",
      "Orthopedics & Joint Replacement",
      "Gastroenterology & Hepatology",
      "Nephrology & Renal Transplant",
      "Critical Care & Pulmonology",
    ],
    agreementTypeNames: [
      "GIPSA Preferred Provider Network (PPN)",
      "Direct MD India TPA Bilateral Agreement",
    ],
    agreements: [
      { providerAgreementId: "AGR-APO-001", providerAgreementName: "GIPSA_PPN_TRIPARTITE_AGREEMENT" },
      { providerAgreementId: "AGR-APO-002", providerAgreementName: "TPA_PROVIDER_BIPARTITE_AGREEMENT" },
    ],
    infrastructure: {
      totalBedCount: 350,
      roomDetailList: [
        { providerBedTypeName: "General Ward", providerBedCount: 160 },
        { providerBedTypeName: "Semi-Private / Twin Sharing", providerBedCount: 70 },
        { providerBedTypeName: "Single Private Room", providerBedCount: 45 },
        { providerBedTypeName: "Intensive Care Unit (ICU)", providerBedCount: 40 },
        { providerBedTypeName: "Neonatal ICU (NICU)", providerBedCount: 15 },
        { providerBedTypeName: "Deluxe Suite", providerBedCount: 20 },
      ],
    },
  },
  HOSP002: {
    providerId: "HOSP002",
    providerName: "Fortis Memorial Research Institute",
    providerType: "HOSPITAL",
    providerTypeId: "HOSP",
    providerTypeName: "Hospital",
    providerClass: "TERTIARY",
    providerSubclass: "SUPER_SPECIALITY",
    providerCode: "MDI-HOSP-002",
    providerIibRohiniCode: "ROH-FOR-77123",
    providerOldCode: JSON.stringify([{ code: "OLD-FOR-102", active: true }]),
    recordStatus: "ACTIVE",
    providerIsVerified: true,
    providerOwnershipType: "Private",
    providerDayCareFlag: true,
    providerCareTier: "Tertiary",
    providerInternalGrade: "A",
    providerOwnerName: "Dr. Ashutosh Raghuvanshi",
    providerOwnerDesignation: "MD & CEO",
    providerOwnerQualification: "MS, MCh (Cardiac Surgery)",
    providerSignatoryName: "Vivek Goyal",
    providerSignatoryDesignation: "Chief Financial Officer",
    providerSystemOfMedicineName: "Allopathy",
    providerSystemOfMedicineId: "MED-001",
    providerEmpanellmentId: "EMP-2024-002",
    providerTpaServicingBranchId: "BR003",
    providerTpaServicingBranchName: "MD India Delhi Regional Office",
    tpaServicingBranchName: "MD India Delhi Regional Office",
    tpaServicingBranchEmail: ["delhi.branch@mdindia.com"],
    providerServiceEmailId: "fortis.servicing@mdindia.com",
    providerAddress: "Sector 44, Opposite HUDA City Centre",
    providerAddressId: "ADDR-002",
    providerPlotNo: "Sector 44",
    providerLocation: "Metro",
    providerTaluka: "Gurugram",
    providerStateCode: "HR",
    providerStateName: "Haryana",
    providerCountryCode: "IN",
    providerLatitude: 28.4595,
    providerLongitude: 77.0266,
    providerAddressStatus: "VERIFIED",
    providerCity: "Gurugram",
    providerDistrict: "Gurugram",
    providerZone: "North",
    providerPostalCode: "122002",
    providerLocationType: "Metro",
    providerNetworkType: "NETWORK",
    tpaProviderNetwork: "NETWORK",
    insurerProviderNetwork: "GIPSA_PPN",
    providerRegistrationNo: "REG-HR-2019-3321",
    providerRegistrationAuthority: "Haryana Directorate General of Health Services",
    providerPanNo: "AAACF5678G",
    providerPanHolderName: "Fortis Healthcare Limited",
    providerTanNo: "DELF12345C",
    providerContactDetail: {
      providerWebsiteAvailableFlag: true,
      providerWebsiteUrl: "https://www.fortishealthcare.com/gurugram",
      providerTelephoneNo: ["0124-4962200"],
      providerFaxNo: ["0124-4962205"],
      providerMobileNo: ["9810012345"],
      providerEmailId: ["fmri.contact@fortishealthcare.com", "tpa.fmri@fortishealthcare.com"],
    },
    identifiers: [
      {
        identifierType: "ROHINI_CODE",
        identifierTypeName: "ROHINI_CODE", isPrimary: true, identifierStatus: "ACTIVE", issuingAuthorityName: "Insurance Information Bureau of India",
        identifierValue: "ROH-FOR-77123",
        validFrom: "2021-04-15",
        validTo: "2026-04-14",
        status: "ACTIVE",
      },
      {
        identifierType: "PAN",
        identifierTypeName: "PAN NO", identifierStatus: "ACTIVE", identifierHolderName: "Apollo Hospitals Enterprise Ltd",
        identifierValue: "AAACF5678G",
        validFrom: "2016-01-10",
        validTo: "2031-12-31",
        status: "ACTIVE",
      },
      {
        identifierType: "NABH",
        identifierTypeName: "NABH Accreditation",
        identifierValue: "NABH-2022-1102",
        validFrom: "2022-05-01",
        validTo: "2028-04-30",
        status: "ACTIVE",
      },
    ],
    certificates: [
      {
        certificateId: "CERT-004",
        type: "NABH",
        description: "NABH Quality Accreditation for Tertiary Care",
        status: "Registered",
        validFrom: "2022-05-01",
        validTo: "2028-04-30",
        registrationNo: "NABH-2022-1102",
        providerActName: "National Accreditation Board for Hospitals",
      },
    ],
    clinicalSpecialties: [
      "Bone Marrow Transplant & Oncology",
      "Neurology & Neuro Surgery",
      "Robotic Joint Replacement",
      "Pediatric Cardiac Surgery",
    ],
    agreementTypeNames: ["Direct MD India TPA Bilateral Agreement"],
    agreements: [
      { providerAgreementId: "AGR-FOR-001", providerAgreementName: "TPA_PROVIDER_BIPARTITE_AGREEMENT" },
    ],
    infrastructure: {
      totalBedCount: 400,
      roomDetailList: [
        { providerBedTypeName: "General Ward", providerBedCount: 180 },
        { providerBedTypeName: "Twin Sharing", providerBedCount: 80 },
        { providerBedTypeName: "Single Room", providerBedCount: 60 },
        { providerBedTypeName: "ICU / CCU", providerBedCount: 50 },
        { providerBedTypeName: "NICU", providerBedCount: 15 },
        { providerBedTypeName: "Suite", providerBedCount: 15 },
      ],
    },
  },
};

export const MOCK_PROVIDER_AGREEMENTS_MAP: Record<string, any[]> = {
  HOSP001: [
    {
      providerAgreementId: "AGR-APO-001",
      providerId: "HOSP001",
      providerAgreementName: "GIPSA Preferred Provider Network Agreement",
      providerAgreementType: "GIPSA_PPN",
      providerAgreementStatus: "ACTIVE",
      effectiveFromDate: "2024-01-01",
      effectiveToDate: "2027-12-31",
      mouSignedDate: "2023-12-15",
      applicableScope: "ALL_INSURERS",
      rateCardType: "GIPSA_STANDARD",
      securityDepositAmount: 500000,
      penaltyClausePercentage: 2.5,
      slaTurnaroundHours: 24,
      recordStatus: "ACTIVE",
      gracePeriodDays: 30,
      noticePeriodDays: 60,
      arbitrationJurisdiction: "Ahmedabad",
      authorizedSignatoryName: "Dr. Suneeta Reddy",
      tpaSignatoryName: "Sanjay Sharma (VP Operations)",
    },
    {
      providerAgreementId: "AGR-APO-002",
      providerId: "HOSP001",
      providerAgreementName: "Direct MD India TPA Bilateral Service Agreement",
      providerAgreementType: "DIRECT_AGREEMENT",
      providerAgreementStatus: "ACTIVE",
      effectiveFromDate: "2023-04-01",
      effectiveToDate: "2026-03-31",
      mouSignedDate: "2023-03-20",
      applicableScope: "CORPORATE_POLICIES",
      rateCardType: "BILATERAL_TARIFF",
      securityDepositAmount: 250000,
      penaltyClausePercentage: 1.5,
      slaTurnaroundHours: 12,
      recordStatus: "ACTIVE",
      gracePeriodDays: 15,
      noticePeriodDays: 45,
      arbitrationJurisdiction: "Pune",
      authorizedSignatoryName: "Dr. Suneeta Reddy",
      tpaSignatoryName: "Rajesh Patil (Head Network)",
    },
  ],
};

export const MOCK_PROVIDER_OWNERS_MAP: Record<string, any[]> = {
  HOSP001: [
    {
      providerOwnerId: "OWN-001",
      providerId: "HOSP001",
      providerOwnerName: "Dr. Prathap C. Reddy",
      providerOwnerPanNo: "AAACA1234F",
      providerOwnerDesignation: "Executive Chairman & Founder",
      providerOwnerQualification: "MD, FRCS (Cardiology)",
      providerOwnerTelephone: ["079-66701800"],
      providerOwnerMobile: ["9876543210"],
      providerOwnerEmailId: ["dr.prathap@apollohospitals.com"],
      providerOwnerGender: "Male",
      providerOwnerAddress: "Plot 1A, GIDC Estate, Gandhinagar Highway",
      providerOwnerState: "Gujarat",
      providerOwnerCity: "Ahmedabad",
      providerOwnerPincode: "382428",
      recordStatus: "ACTIVE",
    },
    {
      providerOwnerId: "OWN-002",
      providerId: "HOSP001",
      providerOwnerName: "Dr. Suneeta Reddy",
      providerOwnerPanNo: "AAACS5678K",
      providerOwnerDesignation: "Managing Director",
      providerOwnerQualification: "MBA, Healthcare Management",
      providerOwnerTelephone: ["079-66701802"],
      providerOwnerMobile: ["9876543211"],
      providerOwnerEmailId: ["suneeta.reddy@apollohospitals.com"],
      providerOwnerGender: "Female",
      providerOwnerAddress: "Plot 1A, GIDC Estate, Gandhinagar Highway",
      providerOwnerState: "Gujarat",
      providerOwnerCity: "Ahmedabad",
      providerOwnerPincode: "382428",
      recordStatus: "ACTIVE",
    },
  ],
};

export const MOCK_PROVIDER_INFRASTRUCTURE_MAP: Record<string, any> = {
  HOSP001: {
    providerInfrastructureId: "INF-001",
    providerId: "HOSP001",
    totalBedCount: 350,
    icuBeds: 40,
    ccuBeds: 15,
    twinSharing: 70,
    suite: 20,
    labourRooms: 6,
    generalBeds: 160,
    singleBeds: 45,
    nicuBeds: 15,
    majorOt: 8,
    minorOt: 4,
    roomDetailList: [
      { providerBedTypeName: "General Ward", providerBedCount: 160 },
      { providerBedTypeName: "Semi-Private / Twin Sharing", providerBedCount: 70 },
      { providerBedTypeName: "Single Private Room", providerBedCount: 45 },
      { providerBedTypeName: "Intensive Care Unit (ICU)", providerBedCount: 40 },
      { providerBedTypeName: "Neonatal ICU (NICU)", providerBedCount: 15 },
      { providerBedTypeName: "Deluxe Suite", providerBedCount: 20 },
    ],
  },
};

export const MOCK_PROVIDER_MANPOWER_MAP: Record<string, any> = {
  HOSP001: {
    providerManpowerId: "MANP-001",
    providerId: "HOSP001",
    manpowerList: [
      {
        providerManpowerDetailId: "MP-001",
        manpowerType: "Full-Time Specialists",
        employmentType: "PERMANENT",
        totalCount: 85,
        onDutyCount: 60,
        onCallCount: 25,
        trainedCount: 85,
        qualificationType: "MD / MS / DNB / DM / MCh",
        experienceYears: 12,
        isActive: true,
      },
      {
        providerManpowerDetailId: "MP-002",
        manpowerType: "Visiting Consultants",
        employmentType: "VISITING",
        totalCount: 45,
        onDutyCount: 15,
        onCallCount: 30,
        trainedCount: 45,
        qualificationType: "Super-Specialist DM / MCh",
        experienceYears: 15,
        isActive: true,
      },
      {
        providerManpowerDetailId: "MP-003",
        manpowerType: "Registered Nursing Staff",
        employmentType: "PERMANENT",
        totalCount: 220,
        onDutyCount: 150,
        onCallCount: 70,
        trainedCount: 220,
        qualificationType: "B.Sc Nursing / GNM",
        experienceYears: 5,
        isActive: true,
      },
      {
        providerManpowerDetailId: "MP-004",
        manpowerType: "Paramedical & Allied Health",
        employmentType: "PERMANENT",
        totalCount: 95,
        onDutyCount: 70,
        onCallCount: 25,
        trainedCount: 95,
        qualificationType: "Diploma / Degree in Medical Lab / Radiology",
        experienceYears: 6,
        isActive: true,
      },
    ],
  },
};

export const MOCK_PROVIDER_FACILITIES_MAP: Record<string, any> = {
  HOSP001: {
    providerFacilityId: "FAC-001",
    providerId: "HOSP001",
    facilityList: [
      {
        providerFacilityDetailId: "FCL-001",
        facilityCategory: "Emergency & Trauma",
        facilityType: "Advanced Trauma Center with Helipad",
        availabilityFlag: true,
        serviceMode: "IN_HOUSE",
        outsourcedVendor: "",
        twentyFourBySevenFlag: true,
        emergencySupportFlag: true,
        operationalStatus: "OPERATIONAL",
        registrationRequiredFlag: true,
        registrationNumber: "TRM-GJ-2021",
        validFrom: "2021-01-01",
        validUpto: "2028-12-31",
        remarks: "Level-1 24x7 Comprehensive Trauma Care Unit",
        isActive: true,
      },
      {
        providerFacilityDetailId: "FCL-002",
        facilityCategory: "Diagnostic Imaging",
        facilityType: "3 Tesla MRI & 128-Slice Dual Source CT",
        availabilityFlag: true,
        serviceMode: "IN_HOUSE",
        outsourcedVendor: "",
        twentyFourBySevenFlag: true,
        emergencySupportFlag: true,
        operationalStatus: "OPERATIONAL",
        registrationRequiredFlag: true,
        registrationNumber: "AERB-RAD-9921",
        validFrom: "2022-03-15",
        validUpto: "2027-03-14",
        remarks: "AERB approved radiation safety compliant",
        isActive: true,
      },
      {
        providerFacilityDetailId: "FCL-003",
        facilityCategory: "Blood Bank & Component",
        facilityType: "NABH Accredited Blood Center",
        availabilityFlag: true,
        serviceMode: "IN_HOUSE",
        outsourcedVendor: "",
        twentyFourBySevenFlag: true,
        emergencySupportFlag: true,
        operationalStatus: "OPERATIONAL",
        registrationRequiredFlag: true,
        registrationNumber: "BB-FDA-GJ-771",
        validFrom: "2020-05-01",
        validUpto: "2026-04-30",
        remarks: "Full apheresis and component separation facility",
        isActive: true,
      },
      {
        providerFacilityDetailId: "FCL-004",
        facilityCategory: "Cardiology Intervention",
        facilityType: "Bi-Plane Cardiac Cath Lab",
        availabilityFlag: true,
        serviceMode: "IN_HOUSE",
        outsourcedVendor: "",
        twentyFourBySevenFlag: true,
        emergencySupportFlag: true,
        operationalStatus: "OPERATIONAL",
        registrationRequiredFlag: true,
        registrationNumber: "CL-2022-09",
        validFrom: "2022-01-10",
        validUpto: "2027-01-09",
        remarks: "Primary PCI and structural heart procedures",
        isActive: true,
      },
      {
        providerFacilityDetailId: "FCL-005",
        facilityCategory: "Renal Care",
        facilityType: "Dialysis Center (24 Machines)",
        availabilityFlag: true,
        serviceMode: "IN_HOUSE",
        outsourcedVendor: "",
        twentyFourBySevenFlag: true,
        emergencySupportFlag: true,
        operationalStatus: "OPERATIONAL",
        registrationRequiredFlag: false,
        registrationNumber: "",
        validFrom: "2021-08-01",
        validUpto: "2027-07-31",
        remarks: "Dedicated negative pressure beds for infected patients",
        isActive: true,
      },
    ],
  },
};

export const MOCK_PROVIDER_CONTACT_PERSONS_MAP: Record<string, any[]> = {
  HOSP001: [
    {
      providerContactPersonId: "CP-001",
      providerId: "HOSP001",
      providerContactPersonRole: "Medical Superintendent",
      providerContactPersonRoleId: "ROLE-MS",
      providerContactPersonPrefix: "Dr.",
      providerContactPersonFirstName: "Anil",
      providerContactPersonMiddleName: "Kumar",
      providerContactPersonLastName: "Sharma",
      providerContactPersonFullName: "Dr. Anil Kumar Sharma",
      providerContactPersonDesignation: "Medical Superintendent & Chief of Staff",
      providerContactPersonTelephoneNo: ["079-66701810"],
      providerContactPersonMobileNo: ["9825012345"],
      providerContactPersonEmailId: ["dr.anil.sharma@apollohospitals.com"],
      providerContactPersonGender: "Male",
      providerContactPersonAddress: "Plot 1A, GIDC Estate, Gandhinagar Highway",
      providerContactPersonState: "Gujarat",
      providerContactPersonCity: "Ahmedabad",
      providerContactPersonPincode: "382428",
      recordStatus: "ACTIVE",
    },
    {
      providerContactPersonId: "CP-002",
      providerId: "HOSP001",
      providerContactPersonRole: "TPA & Insurance Desk Manager",
      providerContactPersonRoleId: "ROLE-TPA",
      providerContactPersonPrefix: "Mr.",
      providerContactPersonFirstName: "Bhavin",
      providerContactPersonMiddleName: "",
      providerContactPersonLastName: "Mehta",
      providerContactPersonFullName: "Bhavin Mehta",
      providerContactPersonDesignation: "Head - Corporate Relations & TPA Helpdesk",
      providerContactPersonTelephoneNo: ["079-66701820"],
      providerContactPersonMobileNo: ["9825123456"],
      providerContactPersonEmailId: ["tpa.desk.ahmedabad@apollohospitals.com"],
      providerContactPersonGender: "Male",
      providerContactPersonAddress: "Plot 1A, GIDC Estate, Gandhinagar Highway",
      providerContactPersonState: "Gujarat",
      providerContactPersonCity: "Ahmedabad",
      providerContactPersonPincode: "382428",
      recordStatus: "ACTIVE",
    },
    {
      providerContactPersonId: "CP-003",
      providerId: "HOSP001",
      providerContactPersonRole: "Billing & Accounts In-Charge",
      providerContactPersonRoleId: "ROLE-BILL",
      providerContactPersonPrefix: "Ms.",
      providerContactPersonFirstName: "Neha",
      providerContactPersonMiddleName: "P.",
      providerContactPersonLastName: "Patel",
      providerContactPersonFullName: "Neha P. Patel",
      providerContactPersonDesignation: "Senior Manager - Hospital Billing & Settlement",
      providerContactPersonTelephoneNo: ["079-66701830"],
      providerContactPersonMobileNo: ["9825234567"],
      providerContactPersonEmailId: ["billing.settlements@apollohospitals.com"],
      providerContactPersonGender: "Female",
      providerContactPersonAddress: "Plot 1A, GIDC Estate, Gandhinagar Highway",
      providerContactPersonState: "Gujarat",
      providerContactPersonCity: "Ahmedabad",
      providerContactPersonPincode: "382428",
      recordStatus: "ACTIVE",
    },
  ],
};

export const MOCK_PROVIDER_NETWORK_MAPPINGS_MAP: Record<string, any[]> = {
  HOSP001: [
    {
      providerNetworkMappingId: "MAP-001",
      providerId: "HOSP001",
      providerName: "Apollo Hospital International",
      insurerId: "INS001",
      insurerCode: "NICL",
      insurerName: "National Insurance Company Limited",
      insurerProviderCode: "NICL-APO-001",
      providerMappingType: "INSURER",
      providerNetworkStatus: "MAPPED",
      providerNetworkIsActive: true,
      effectiveFrom: "2024-01-01",
      effectiveTo: "2027-12-31",
      networkMode: "GIPSA_PPN",
      tariffType: "STANDARD_PPN",
      bankMatchWithIC: "MATCHED",
      remarks: "Active cashless empanelment under GIPSA PPN",
    },
    {
      providerNetworkMappingId: "MAP-002",
      providerId: "HOSP001",
      providerName: "Apollo Hospital International",
      insurerId: "INS002",
      insurerCode: "NIACL",
      insurerName: "New India Assurance Co. Ltd",
      insurerProviderCode: "NIA-APO-552",
      providerMappingType: "INSURER",
      providerNetworkStatus: "MAPPED",
      providerNetworkIsActive: true,
      effectiveFrom: "2024-01-01",
      effectiveTo: "2027-12-31",
      networkMode: "GIPSA_PPN",
      tariffType: "STANDARD_PPN",
      bankMatchWithIC: "MATCHED",
      remarks: "Active cashless empanelment under GIPSA PPN",
    },
    {
      providerNetworkMappingId: "MAP-003",
      providerId: "HOSP001",
      providerName: "Apollo Hospital International",
      insurerId: "INS003",
      insurerCode: "OICL",
      insurerName: "Oriental Insurance Company Limited",
      insurerProviderCode: "OIC-APO-883",
      providerMappingType: "INSURER",
      providerNetworkStatus: "MAPPED",
      providerNetworkIsActive: true,
      effectiveFrom: "2024-01-01",
      effectiveTo: "2027-12-31",
      networkMode: "GIPSA_PPN",
      tariffType: "STANDARD_PPN",
      bankMatchWithIC: "MATCHED",
      remarks: "Active cashless empanelment under GIPSA PPN",
    },
    {
      providerNetworkMappingId: "MAP-004",
      providerId: "HOSP001",
      providerName: "Apollo Hospital International",
      insurerId: "INS004",
      insurerCode: "UIIC",
      insurerName: "United India Insurance Company Limited",
      insurerProviderCode: "UII-APO-441",
      providerMappingType: "INSURER",
      providerNetworkStatus: "MAPPED",
      providerNetworkIsActive: true,
      effectiveFrom: "2024-01-01",
      effectiveTo: "2027-12-31",
      networkMode: "GIPSA_PPN",
      tariffType: "STANDARD_PPN",
      bankMatchWithIC: "MATCHED",
      remarks: "Active cashless empanelment under GIPSA PPN",
    },
    {
      providerNetworkMappingId: "MAP-005",
      providerId: "HOSP001",
      providerName: "Apollo Hospital International",
      insurerId: "INS005",
      insurerCode: "ICICI_LOMBARD",
      insurerName: "ICICI Lombard General Insurance Co.",
      insurerProviderCode: "IL-APO-092",
      providerMappingType: "INSURER",
      providerNetworkStatus: "MAPPED",
      providerNetworkIsActive: true,
      effectiveFrom: "2023-06-01",
      effectiveTo: "2026-05-31",
      networkMode: "DIRECT_AGREEMENT",
      tariffType: "PREFERRED_TIER_1",
      bankMatchWithIC: "MATCHED",
      remarks: "Bilateral Corporate & Retail cashless tie-up",
    },
  ],
};

export const MOCK_PROVIDER_BANK_ACCOUNTS_MAP: Record<string, any> = {
  HOSP001: {
    providerBankId: "BNK-001",
    providerId: "HOSP001",
    providerBankIfscIsVerified: true,
    providerAccountType: "CURRENT",
    providerBankAccountBeneficiaryType: "HOSPITAL",
    providerBankName: "HDFC Bank Ltd",
    providerBankBranch: "Gandhinagar Highway Branch",
    providerBankIfscCode: "HDFC0000123",
    providerBankMicrCode: "380240002",
    providerBankHolderName: "Apollo Hospitals Enterprise Ltd",
    providerBankAccountNo: "50200012345678",
    providerBankAccountNoMasked: "502000XXXXXX78",
    providerBankBeneficiaryName: "Apollo Hospitals Enterprise Ltd",
    providerBankAddress: "Plot 1A, GIDC Estate, Gandhinagar Highway, Ahmedabad - 382428",
    providerBankIsPrimary: true,
    recordStatus: "ACTIVE",
    providerPanNo: "AAACA1234F",
    providerPanHolderName: "Apollo Hospitals Enterprise Ltd",
    providerTanNo: "AHMA12345B",
    cancelChequeFileMetadataId: "DOC-CHQ-001",
    panCardFileMetadataId: "DOC-PAN-001",
    providerBankKycDocuments: [
      {
        documentType: "CANCELLED_CHEQUE",
        fileName: "Apollo_Cancelled_Cheque_HDFC.pdf",
        status: "VERIFIED",
        verifiedAt: "2024-01-15T11:00:00Z",
      },
      {
        documentType: "PAN_CARD",
        fileName: "Apollo_Hospitals_PAN_Card.pdf",
        status: "VERIFIED",
        verifiedAt: "2024-01-15T11:00:00Z",
      },
    ],
  },
};

export const MOCK_PROVIDER_SOC_MAP: Record<string, any[]> = {
  HOSP001: [
    {
      providerSocId: "SOC-001",
      providerId: "HOSP001",
      providerSocName: "GIPSA PPN Tariff Schedule 2024",
      socName: "GIPSA PPN Tariff Schedule 2024",
      providerSocVersion: "v2.1",
      providerSocCode: "SOC-APO-2024",
      socIdVersion: "SOC-APO-2024 / v2.1",
      providerSocEffectiveFrom: "2024-01-01",
      providerSocEffectiveTo: "2027-12-31",
      effectiveFrom: "2024-01-01",
      effectiveTo: "2027-12-31",
      isActive: true,
      recordStatus: "ACTIVE",
      providerAgreementId: "AGR-APO-001",
      providerAgreementName: "GIPSA Preferred Provider Network Agreement",
      applicableIcs: "NICL, NIACL, OICL, UIIC",
      insurerMappings: [
        { insurerId: "INS001", insurerName: "National Insurance Co.", effectiveFrom: "2024-01-01" },
        { insurerId: "INS002", insurerName: "New India Assurance", effectiveFrom: "2024-01-01" },
        { insurerId: "INS003", insurerName: "Oriental Insurance", effectiveFrom: "2024-01-01" },
        { insurerId: "INS004", insurerName: "United India Insurance", effectiveFrom: "2024-01-01" },
      ],
      lastUpdatedOn: "2024-01-10T14:30:00Z",
      fileMetadataId: "DOC-SOC-001",
      downloadUrl: "/files/Apollo_GIPSA_Tariff_2024.pdf",
    },
    {
      providerSocId: "SOC-002",
      providerId: "HOSP001",
      providerSocName: "MD India Corporate Rate Schedule",
      socName: "MD India Corporate Rate Schedule",
      providerSocVersion: "v1.4",
      providerSocCode: "SOC-CORP-2023",
      socIdVersion: "SOC-CORP-2023 / v1.4",
      providerSocEffectiveFrom: "2023-04-01",
      providerSocEffectiveTo: "2026-03-31",
      effectiveFrom: "2023-04-01",
      effectiveTo: "2026-03-31",
      isActive: true,
      recordStatus: "ACTIVE",
      providerAgreementId: "AGR-APO-002",
      providerAgreementName: "Direct MD India TPA Bilateral Service Agreement",
      applicableIcs: "All Corporate Clients",
      insurerMappings: [
        { insurerId: "INS005", insurerName: "ICICI Lombard", effectiveFrom: "2023-06-01" },
      ],
      lastUpdatedOn: "2023-03-25T10:15:00Z",
      fileMetadataId: "DOC-SOC-002",
      downloadUrl: "/files/Apollo_Corporate_Tariff_2023.pdf",
    },
  ],
};

export const MOCK_PROVIDER_DISCOUNT_CONFIG_MAP: Record<string, any[]> = {
  HOSP001: [
    {
      providerDiscountConfigurationId: "DISC-CFG-001",
      providerId: "HOSP001",
      providerName: "Apollo Hospital International",
      providerAgreementId: "AGR-APO-001",
      providerAgreementName: "GIPSA Preferred Provider Network Agreement",
      providerAgreementType: "GIPSA_PPN",
      corporateSpecificFlag: false,
      providerDiscountStatus: "ACTIVE",
      providerDiscountEffectiveFrom: "2024-01-01",
      providerDiscountEffectiveTo: "2027-12-31",
      remark: "Standard GIPSA Network agreed institutional discount structure",
      insurerApplicability: "ALL",
      corporateApplicability: "ALL",
      discountTypeDetails: [
        {
          providerDiscountTypeDetailId: "DTD-001",
          providerDiscountTypeMasterId: "DISC-001",
          providerDiscountTypeName: "IPD Comprehensive Bill Discount",
          providerServiceType: "IPD",
          providerDiscountPercentage: 15.0,
          providerDiscountAmount: null,
          providerSocId: "SOC-001",
          providerSocName: "GIPSA PPN Tariff Schedule 2024",
          providerSocCode: "SOC-APO-2024",
          isActive: true,
          subtypeDetails: [],
          inclusions: [],
          exclusions: [],
        },
        {
          providerDiscountTypeDetailId: "DTD-002",
          providerDiscountTypeMasterId: "DISC-002",
          providerDiscountTypeName: "OPD Consultation Discount",
          providerServiceType: "OPD",
          providerDiscountPercentage: 10.0,
          providerDiscountAmount: null,
          providerSocId: "SOC-001",
          providerSocName: "GIPSA PPN Tariff Schedule 2024",
          providerSocCode: "SOC-APO-2024",
          isActive: true,
          subtypeDetails: [],
          inclusions: [],
          exclusions: [],
        },
        {
          providerDiscountTypeDetailId: "DTD-003",
          providerDiscountTypeMasterId: "DISC-003",
          providerDiscountTypeName: "In-House Investigation & Diagnostics",
          providerServiceType: "DIAGNOSTICS",
          providerDiscountPercentage: 12.0,
          providerDiscountAmount: null,
          providerSocId: "SOC-001",
          providerSocName: "GIPSA PPN Tariff Schedule 2024",
          providerSocCode: "SOC-APO-2024",
          isActive: true,
          subtypeDetails: [],
          inclusions: [],
          exclusions: [],
        },
        {
          providerDiscountTypeDetailId: "DTD-004",
          providerDiscountTypeMasterId: "DISC-004",
          providerDiscountTypeName: "In-House Pharmacy Discount",
          providerServiceType: "PHARMACY",
          providerDiscountPercentage: 8.0,
          providerDiscountAmount: null,
          providerSocId: "SOC-001",
          providerSocName: "GIPSA PPN Tariff Schedule 2024",
          providerSocCode: "SOC-APO-2024",
          isActive: true,
          subtypeDetails: [],
          inclusions: [],
          exclusions: [],
        },
      ],
    },
    {
      providerDiscountConfigurationId: "DISC-CFG-002",
      providerId: "HOSP001",
      providerName: "Apollo Hospital International",
      providerAgreementId: "AGR-APO-002",
      providerAgreementName: "Direct MD India TPA Bilateral Service Agreement",
      providerAgreementType: "DIRECT_AGREEMENT",
      corporateSpecificFlag: true,
      providerDiscountStatus: "ACTIVE",
      providerDiscountEffectiveFrom: "2023-04-01",
      providerDiscountEffectiveTo: "2026-03-31",
      remark: "Special corporate employee discount package",
      insurerApplicability: "SELECTED",
      corporateApplicability: "SELECTED",
      discountTypeDetails: [
        {
          providerDiscountTypeDetailId: "DTD-005",
          providerDiscountTypeMasterId: "DISC-001",
          providerDiscountTypeName: "Corporate Executive IPD Discount",
          providerServiceType: "IPD",
          providerDiscountPercentage: 18.0,
          providerDiscountAmount: null,
          providerSocId: "SOC-002",
          providerSocName: "MD India Corporate Rate Schedule",
          providerSocCode: "SOC-CORP-2023",
          isActive: true,
          subtypeDetails: [],
          inclusions: [],
          exclusions: [],
        },
      ],
    },
  ],
};
