/** Field keys for `GET /v1/staging-bank-provider-insurer`. */
export const STAGING_BANK_PROVIDER_INSURER_API_KEYS = {
  stagingBankProviderInsurerId: "stagingBankProviderInsurerId",
  inwardNo: "inwardNo",
  insurerId: "insurerId",
  isValid: "isValid",
  providerStagingStatus: "providerStagingStatus",
  insurerProviderCode: "insurerProviderCode",
  providerName: "providerName",
  providerStatus: "providerStatus",
  providerIibRohiniCode: "providerIibRohiniCode",
  providerPanNumber: "providerPanNumber",
  providerEffectiveFrom: "providerEffectiveFrom",
  providerBankAccountNumber: "providerBankAccountNumber",
  providerBankAccountType: "providerBankAccountType",
  providerBankAccountIfscCode: "providerBankAccountIfscCode",
  providerAddress: "providerAddress",
  providerAddressCity: "providerAddressCity",
  providerAddressStateName: "providerAddressStateName",
  providerAddressPostalCode: "providerAddressPostalCode",
  providerBankRemark: "providerBankRemark",
  createdAt: "createdAt",
  updatedAt: "updatedAt",
} as const;

export const STAGING_BANK_PROVIDER_INSURER_COUNT_KEYS = {
  totalReceived: "totalReceived",
  total: "total",
  processedCount: "processedCount",
  processed: "processed",
  failedCount: "failedCount",
  failed: "failed",
  providerNotFoundCount: "providerNotFoundCount",
  providerNotFound: "providerNotFound",
  matchedCount: "matchedCount",
  matched: "matched",
  notMatchedCount: "notMatchedCount",
  notMatched: "notMatched",
  pendingFromIc: "pendingFromIc",
  pendingCount: "pendingCount",
  pending: "pending",
  bankDetailsMissingCount: "bankDetailsMissingCount",
  bankDetailsMissing: "bankDetailsMissing",
  validationFailedCount: "validationFailedCount",
  processingFailedCount: "processingFailedCount",
} as const;
